// nun-data.js — Nomenclador Único Nacional de Ortopedia y Traumatología (AAOT), 6ª edición 2022.
// Generado desde 'NUN 6 EDICION.pdf'. Solo datos + helpers de lookup. No hace fetch.
// Se usa en el módulo Débitos para validar/describir códigos NUN y armar el payload del auditor.

var NUN_EDICION = '6ª edición (2022)';
var NUN_REGIONES = {"CO": "Columna vertebral", "MS": "Miembro superior", "PC": "Pelvis y cadera", "RO": "Rodilla", "PP": "Pierna y pie"};

// Texto de Normas Primarias y Secundarias (referencia rápida en la UI).
var NUN_NORMAS = "NORMAS PRIMARIAS\n\n1. COMPLEJIDADES\n   a) Se puede facturar UNA SOLA complejidad por intervención (excepción: Norma Primaria Nº 2).\n   b) Prácticas múltiples por la misma vía, inherentes a la misma patología, no especificadas en el Nomenclador: se factura la complejidad de MAYOR valor.\n   c) Si no existe una práctica en una región, se homologa a una similar de otra región.\n\n2. INTERVENCIONES MÚLTIPLES O SIMULTÁNEAS\n   a) Intervenciones múltiples (distintas vías por distintas patologías no especificadas), simultáneas (distintos equipos) o sucesivas (mismo equipo), homolateral o bilateral: se facturan las complejidades por separado, 100% de cada una.\n   b) Patologías por doble vía (no especificadas) en el mismo tiempo quirúrgico: +50% sobre el valor de la complejidad correspondiente.\n   c) Patologías por doble vía (no especificadas) en diferentes actos quirúrgicos: 100% del código que corresponda en cada acto.\n   d) Tratamiento de dos patologías diferentes sin relación entre sí (no especificadas), misma vía de abordaje, mismo acto quirúrgico: +50% al código de la segunda patología.\n\n3. REINTERVENCIONES: revisiones de recidiva o complicación de cualquier patología o complejidad (no especificadas): +30% sobre el valor de la complejidad original.\n\n4. INJERTOS ÓSEOS (no especificados en el código): se agrega al código el porcentaje según tipo:\n   - 25% injerto óseo autólogo\n   - 15% injerto óseo de Banco de Tejidos\n   - 5% sustituto óseo\n\nNORMAS SECUNDARIAS\n\n1. EDADES EXTREMAS: pacientes de hasta 10 años o mayores de 65 años: +20% sobre la complejidad correspondiente.\n2. HORARIO NOCTURNO / FIN DE SEMANA / FERIADO: +20% al código. Nocturno = 21 a 7 h; fin de semana = sábado 12 h a lunes 7 h; feriado = 7 h del día a 7 h del día siguiente.\n3. EMERGENCIA: +20% sobre el código, aun en días/horas hábiles. NO acumulable con la Norma Secundaria Nº 2 ni con la Nº 1. Cirugía de emergencia = la que debe hacerse de inmediato al ingreso y que por su gravedad no puede postergarse (riesgo de vida, viabilidad o función de un miembro).\n   AYUDANTES: complejidades 1 a 4 llevan 1 ayudante; complejidad 5 en adelante llevan 2 ayudantes. Cada ayudante factura +20% del valor convenido para el cirujano. Un 3er ayudante requiere solicitud expresa y fundada a la OS/Prepaga.\n4. USO DE RADIOSCOPÍA: si la práctica la requiere, +5% al código por su utilización.\n5. Los honorarios del especialista incluyen toda la atención del día de la intervención. Visitas pre y post operatorias EN INTERNACIÓN (incluido el día del alta) se facturan individualmente por día.\n\nESTRUCTURA DEL CÓDIGO: RR.CC.OO — RR = región (CO columna vertebral, MS miembro superior, PC pelvis y cadera, RO rodilla, PP pierna y pie); CC = complejidad (01 a 10); OO = número de orden dentro de la grilla. Las complejidades ordenan la ponderación del honorario de menor (1) a mayor (10); el valor en $ de cada complejidad lo fija cada convenio OS/ART, no el Nomenclador.";

// Listado completo de códigos: { codigo, region, complejidad, orden, texto }
var NUN_CODIGOS = [
  {c:"CO.01.01",r:"CO",x:1,o:1,t:"Infiltraciones."},
  {c:"CO.01.02",r:"CO",x:1,o:2,t:"Collar de yeso."},
  {c:"CO.01.03",r:"CO",x:1,o:3,t:"Sutura de herida simple, no quirúrgica."},
  {c:"CO.02.01",r:"CO",x:2,o:1,t:"Minerva de yeso."},
  {c:"CO.02.02",r:"CO",x:2,o:2,t:"Corsé de yeso. Corsé de Risser."},
  {c:"CO.02.03",r:"CO",x:2,o:3,t:"Tracción cefálica."},
  {c:"CO.02.04",r:"CO",x:2,o:4,t:"Infiltración facetaria o sacroilíaca guiada por radioscopia o tomografía axial computarizada."},
  {c:"CO.02.05",r:"CO",x:2,o:5,t:"Drenaje y toilette de absceso superficial supraaponeurótico."},
  {c:"CO.03.01",r:"CO",x:3,o:1,t:"Tracción craneopelviana o craneofemoral."},
  {c:"CO.03.02",r:"CO",x:3,o:2,t:"Halo chaleco. Halo silla."},
  {c:"CO.03.03",r:"CO",x:3,o:3,t:"Bloqueo analgésico peridural o foraminal guiado por tomografía o radioscopia"},
  {c:"CO.03.04",r:"CO",x:3,o:4,t:"Tratamiento con radiofrecuencia."},
  {c:"CO.03.05",r:"CO",x:3,o:5,t:"Punción biopsia."},
  {c:"CO.04.01",r:"CO",x:4,o:1,t:"Biopsias a cielo abierto. Biopsia guiada por imágenes por causa oncológica."},
  {c:"CO.05.01",r:"CO",x:5,o:1,t:"Resecciones parciales óseas como único tratamiento: laminectomía, foraminectomía, apófisis transversas, facetectomía, etc."},
  {c:"CO.05.02",r:"CO",x:5,o:2,t:"Extracción de material de osteosíntesis correspondiente hasta 4 niveles."},
  {c:"CO.05.03",r:"CO",x:5,o:3,t:"Toilette quirúrgica infecciones, sin retiro de material de osteosíntesis."},
  {c:"CO.05.04",r:"CO",x:5,o:4,t:"Distracción semestral progresiva de columna."},
  {c:"CO.05.05",r:"CO",x:5,o:5,t:"Tumores Benignos o de baja agresividad menores de 3 cm en región dorsal o lumbar paravertebral."},
  {c:"CO.05.06",r:"CO",x:5,o:6,t:"Procedimientos terapéuticos percutáneos guiados por imágenes. (Tratamiento del quiste óseo, simple, termo-ablación percutánea, crio-ablación percutánea, alcoholización)"},
  {c:"CO.06.01",r:"CO",x:6,o:1,t:"Retiro de material de osteosíntesis correspondiente a 5 niveles o más."},
  {c:"CO.06.02",r:"CO",x:6,o:2,t:"Toilette quirúrgica en infecciones con retiro de material de osteosíntesis."},
  {c:"CO.06.03",r:"CO",x:6,o:3,t:"Tumores Benignos o de baja agresividad mayores de 3 cm en región dorsal o lumbar para vertebral."},
  {c:"CO.06.04",r:"CO",x:6,o:4,t:"Ampliaciones de márgenes en cirugía de tumores de bajo grado."},
  {c:"CO.07.01",r:"CO",x:7,o:1,t:"Discectomía lumbar simple por vía posterior."},
  {c:"CO.07.02",r:"CO",x:7,o:2,t:"Canal estrecho simple. Liberación sacodural de hasta 2 niveles sin instrumentación con artrodesis simple o sin ella."},
  {c:"CO.07.03",r:"CO",x:7,o:3,t:"Espondilólisis. Espondilolistesis lumbosacra; artrodesis simple, no instrumentada."},
  {c:"CO.07.04",r:"CO",x:7,o:4,t:"Artrodesis simple de columna cervical por vía posterior."},
  {c:"CO.07.05",r:"CO",x:7,o:5,t:"Vertebroplastía y costoplastía. Laminoplastía."},
  {c:"CO.07.06",r:"CO",x:7,o:6,t:"Procedimientos tendinosos múltiples: más de tres distribuidos en uno o ambos lados. Procedimientos óseos en un solo nivel con procedimientos tendinosos asociados en cualquier nivel (en enfermedades neuroortopédicas)"},
  {c:"CO.07.07",r:"CO",x:7,o:7,t:"Resecciones parciales óseas como único tratamiento de tumores benignos: laminectomía, foraminectomía, apófisis transversas, facetectomía, etc."},
  {c:"CO.08.01",r:"CO",x:8,o:1,t:"Discectomía lumbar más artrodesis con instrumentación. Instrumentación hasta 2 niveles."},
  {c:"CO.08.02",r:"CO",x:8,o:2,t:"Espondilolistesis, artrodesis instrumentada hasta 3 niveles."},
  {c:"CO.08.03",r:"CO",x:8,o:3,t:"Canal estrecho degenerativo: liberación sacodural hasta 3 niveles más instrumentación. Recalibrado de canal."},
  {c:"CO.08.04",r:"CO",x:8,o:4,t:"Inestabilidad postraumática y fracturas de columna cervical, dorsal y lumbar por vía posterior, hasta 4 niveles. Con lesión de duramadre o sin ella."},
  {c:"CO.08.05",r:"CO",x:8,o:5,t:"Discectomía cervical por vía anterior. Con instrumentación o sin ella."},
  {c:"CO.08.06",r:"CO",x:8,o:6,t:"Seudoartrosis a cualquier nivel, sin retiro ni cambio de instrumentación."},
  {c:"CO.08.07",r:"CO",x:8,o:7,t:"Discectomía cervical-dorsal por abordajes posteriores, con instrumentación o sin ella"},
  {c:"CO.08.08",r:"CO",x:8,o:8,t:"Artrodesis simple de columna dorsal por vía anterior."},
  {c:"CO.08.09",r:"CO",x:8,o:9,t:"Canal estrecho cervical: liberación anterior medular y por misma vía artrodesis instrumentada hasta 2 niveles."},
  {c:"CO.08.10",r:"CO",x:8,o:10,t:"Artrodesis circunferencial de 360º, por vía posterior, de un nivel, con colocación de PLIF- TLIF o sin ella."},
  {c:"CO.08.11",r:"CO",x:8,o:11,t:"Colocación de instrumental para distracción progresiva de columna."},
  {c:"CO.09.01",r:"CO",x:9,o:1,t:"Canal estrecho degenerativo: estrecho lumbar liberación sacodural de 4 o más niveles, más instrumentación."},
  {c:"CO.09.02",r:"CO",x:9,o:2,t:"Espondilólisis, espondilolistesis lumbar, artrodesis instrumentada de 4 niveles o más."},
  {c:"CO.09.03",r:"CO",x:9,o:3,t:"Discectomía cervical/dorsal por vía anterior y posterior. Costotransversectomía."},
  {c:"CO.09.04",r:"CO",x:9,o:4,t:"Discectomía lumbar/dorsal endoscópica asistida por video."},
  {c:"CO.09.05",r:"CO",x:9,o:5,t:"Laminoplastia cervical, con instrumentación o sin ella."},
  {c:"CO.09.06",r:"CO",x:9,o:6,t:"Artrodesis cervical anterior con instrumentación."},
  {c:"CO.09.07",r:"CO",x:9,o:7,t:"Toracoscopia: artrodesis."},
  {c:"CO.09.08",r:"CO",x:9,o:8,t:"Luxofracturas cervicales, dorsales y lumbares. Estabilización instrumentada por vía anterior."},
  {c:"CO.09.09",r:"CO",x:9,o:9,t:"Fracturas cervicales, dorsales y lumbares. Artrodesis e instrumentación por vía posterior de 5 niveles o más. Con lesión de duramadre o sin ella."},
  {c:"CO.09.10",r:"CO",x:9,o:10,t:"Artrodesis lumbar anterior con instrumentación o sin ella."},
  {c:"CO.09.11",r:"CO",x:9,o:11,t:"Artrodesis de 360º en uno o más niveles por vía posterior."},
  {c:"CO.09.12",r:"CO",x:9,o:12,t:"Artrodesis instrumentada de columna dorsal por vía anterior."},
  {c:"CO.09.13",r:"CO",x:9,o:13,t:"Canal estrecho cervical: liberación anterior medular y por misma vía artrodesis instrumentada de 3 niveles o más."},
  {c:"CO.09.14",r:"CO",x:9,o:14,t:"Artrodesis lumbar anterior. Discectomía hasta un nivel."},
  {c:"CO.09.15",r:"CO",x:9,o:15,t:"Artrodesis circunferencial de 360º, por vía posterior, de 2 niveles o más, con colocación de PLIF-TLIF o sin ella."},
  {c:"CO.09.16",r:"CO",x:9,o:16,t:"Reemplazo discal protésico."},
  {c:"CO.09.17",r:"CO",x:9,o:17,t:"Ampliaciones de márgenes en cirugías realizadas en tumores de alto grado en columna o sacro."},
  {c:"CO.10.01",r:"CO",x:10,o:1,t:"Osteomielitis aguda o crónica. Desbridamiento, drenaje (cualquier vía), retiro de material (si corresponde), liberación y nueva estabilización."},
  {c:"CO.10.02",r:"CO",x:10,o:2,t:"Malformaciones congénitas de columna: tratamiento quirúrgico."},
  {c:"CO.10.03",r:"CO",x:10,o:3,t:"Tumores vertebrales (resección oncológica con o sin osteosíntesis más artrodesis). Por vía anterior y posterior."},
  {c:"CO.10.04",r:"CO",x:10,o:4,t:"Escoliosis, lordosis, cifosis. Corrección quirúrgica por vía anterior o posterior. Osteotomía de columna."},
  {c:"CO.10.05",r:"CO",x:10,o:5,t:"Seudoartrosis a cualquier nivel con retiro de instrumentación rota y nueva instrumentación."},
  {c:"MS.01.01",r:"MS",x:1,o:1,t:"Infiltración diagnóstica o terapéutica"},
  {c:"MS.01.02",r:"MS",x:1,o:2,t:"Inmovilizaciones enyesadas, yesos localizadores. Confección y aplicación de una férula dinámica (para un dedo o más de uno)"},
  {c:"MS.01.03",r:"MS",x:1,o:3,t:"Sutura de herida simple, no quirúrgica."},
  {c:"MS.01.04",r:"MS",x:1,o:4,t:"Extracción de osteodesis percutáneas en consultorio."},
  {c:"MS.01.05",r:"MS",x:1,o:5,t:"Movilización articular con anestesia."},
  {c:"MS.01.06",r:"MS",x:1,o:6,t:"Extirpación de una uña (como único procedimiento)"},
  {c:"MS.01.07",r:"MS",x:1,o:7,t:"Bloqueo anestésico del plexo braquial, de un nervio periférico o del simpático cervical (como único procedimiento), por cada sesión."},
  {c:"MS.01.08",r:"MS",x:1,o:8,t:"Ligadura arterial o venosa (como único procedimiento)"},
  {c:"MS.01.09",r:"MS",x:1,o:9,t:"Arteriografía o flexografía por punción o a cielo abierto (como único procedimiento)"},
  {c:"MS.01.10",r:"MS",x:1,o:10,t:"Drenaje, biopsia o extirpación de una adenopatía cervical, axilar o epitroclear."},
  {c:"MS.01.11",r:"MS",x:1,o:11,t:"Drenaje de un hematoma subungueal, por medio de la perforación única o múltiple de la uña."},
  {c:"MS.01.12",r:"MS",x:1,o:12,t:"Abordaje quirúrgico y evacuación de un hematoma subcutáneo supraponeurótico."},
  {c:"MS.01.13",r:"MS",x:1,o:13,t:"Artrografía o artroneumografía por punción, en medio quirúrgico y con intensificador de imágenes."},
  {c:"MS.01.14",r:"MS",x:1,o:14,t:"Tracción de partes blandas."},
  {c:"MS.01.15",r:"MS",x:1,o:15,t:"Examen radiológico con anestesia (general o regional)"},
  {c:"MS.01.16",r:"MS",x:1,o:16,t:"Cualquier otra práctica incruenta no especificada en los anteriores puntos."},
  {c:"MS.02.01",r:"MS",x:2,o:1,t:"Yeso toracobraquial."},
  {c:"MS.02.02",r:"MS",x:2,o:2,t:"Yesos o férulas dinámicos"},
  {c:"MS.02.03",r:"MS",x:2,o:3,t:"Reducción cerrada de fracturas o luxaciones en forma incruenta, con anestesia local, plexual o general. Incluye inmovilización enyesada"},
  {c:"MS.02.04",r:"MS",x:2,o:4,t:"Extracción de clavijas percutáneas con anestesia local o general en quirófano"},
  {c:"MS.02.05",r:"MS",x:2,o:5,t:"Tracciones esqueléticas"},
  {c:"MS.02.06",r:"MS",x:2,o:6,t:"Toilette quirúrgica superficial (supraaponeurótica)"},
  {c:"MS.02.07",r:"MS",x:2,o:7,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, hasta 2 grupos musculares, unilateral o bilateral"},
  {c:"MS.02.08",r:"MS",x:2,o:8,t:"Tenotomía de un tendón flexor o extensor en el antebrazo, la muñeca, la mano o un dedo"},
  {c:"MS.02.09",r:"MS",x:2,o:9,t:"Zetaplastia para corrección de una cicatriz."},
  {c:"MS.02.10",r:"MS",x:2,o:10,t:"Extirpación radical de una uña y la matriz ungueal. Incluye eventual injerto de piel"},
  {c:"MS.02.11",r:"MS",x:2,o:11,t:"Corrección de deformidades ungueales por medio de la extirpación de la uña y la corrección de irregularidades en el lecho ungueal"},
  {c:"MS.02.12",r:"MS",x:2,o:12,t:"Sección del pedículo de un colgajo. Diferido de un colgajo, por cada tiempo"},
  {c:"MS.02.13",r:"MS",x:2,o:13,t:"Tratamiento de quemaduras: toilette quirúrgica, evacuación de flictenas, descompresión por medio de incisiones en la piel o escaras cutáneas en medio quirúrgico, con anestesia o sin ella. Incluye eventual inmovilización. Curación de quemaduras (con anestesia o sin ella), en medio quirúrgico"},
  {c:"MS.02.14",r:"MS",x:2,o:14,t:"Extirpación de una lesión seudotumoral, de la sinovial de una articulación de un dedo."},
  {c:"MS.02.15",r:"MS",x:2,o:15,t:"Extirpación de una lesión cutánea benigna (verruga vulgar, botriomicoma, queratoacantoma, hemangioma cutáneo localizado, etc.)"},
  {c:"MS.02.16",r:"MS",x:2,o:16,t:"Extirpación de un ganglión de una vaina tendinosa digital"},
  {c:"MS.02.17",r:"MS",x:2,o:17,t:"Extirpación de un quiste mucoide del dorso de un dedo. Incluye eventual injerto de piel"},
  {c:"MS.02.18",r:"MS",x:2,o:18,t:"Tratamiento quirúrgico de panadizos (antracoide, periungueal, subungueal, subcutáneo del pulpejo o de la 1ª o 2ª falange)"},
  {c:"MS.02.19",r:"MS",x:2,o:19,t:"Abordaje y extracción de un cuerpo extraño de las partes blandas."},
  {c:"MS.02.20",r:"MS",x:2,o:20,t:"Extracción de tutor externo como único procedimiento"},
  {c:"MS.03.01",r:"MS",x:3,o:1,t:"Fracturas diafisarias de falanges y metacarpianos. Osteodesis"},
  {c:"MS.03.02",r:"MS",x:3,o:2,t:"Fasciotomía subcutánea de la palma de la mano"},
  {c:"MS.03.03",r:"MS",x:3,o:3,t:"Sinovectomía total metacarpofalángica o interfalángica"},
  {c:"MS.03.04",r:"MS",x:3,o:4,t:"Sinovectomía radiocarpiana, intercarpiana o radiocubital inferior, como único procedimiento en esa articulación"},
  {c:"MS.03.05",r:"MS",x:3,o:5,t:"Tenosinovectomía del retináculo dorsal"},
  {c:"MS.03.06",r:"MS",x:3,o:6,t:"Injerto libre, parcial o total de piel como único tratamiento en dedos. Incluye tratamiento del lecho dador"},
  {c:"MS.03.07",r:"MS",x:3,o:7,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, 3 o 4 grupos musculares o más, unilateral o bilateral"},
  {c:"MS.03.08",r:"MS",x:3,o:8,t:"Tratamiento quirúrgico de una tenosinovitis aguda supurada digital o digito-palmo- carpiana"},
  {c:"MS.03.09",r:"MS",x:3,o:9,t:"Tratamiento quirúrgico de un absceso de un espacio aponeurótico de la mano u otro sitio del MS (tenar, hipotenar, palmar medio, comisural, subcutáneo dorsal, subaponeurótico dorsal, del espacio de Parona, etc.). Drenaje de absceso o colección por punción bajo ecografía."},
  {c:"MS.03.10",r:"MS",x:3,o:10,t:"Neurotomías o denervaciones a cielo abierto o por vía artroscópica, en cualquier lugar del MS"},
  {c:"MS.03.11",r:"MS",x:3,o:11,t:"Amputación quirúrgica o desarticulación a nivel de una articulación metacarpofalángica, de un dedo o parte de un dedo"},
  {c:"MS.03.12",r:"MS",x:3,o:12,t:"Luxación o lesiones ligamentarias de la articulación radiocubital distal. Reducción y enclavijado percutáneo"},
  {c:"MS.03.13",r:"MS",x:3,o:13,t:"Tallado y aplicación de un colgajo rotatorio de vecindad"},
  {c:"MS.03.14",r:"MS",x:3,o:14,t:"Biopsias por punción a cualquier nivel (Excluye causas oncológicas)"},
  {c:"MS.04.01",r:"MS",x:4,o:1,t:"Fracturas diafisarias de metacarpianas y falanges (hasta 2). Reducción y osteosíntesis. Más de 2, agregar un 30% al valor de dicha complejidad por cada hueso comprometido. Fractura de Bennett o Rolando."},
  {c:"MS.04.02",r:"MS",x:4,o:2,t:"Fracturas de cúbito, radio o húmero. Reducción y osteodesis."},
  {c:"MS.04.03",r:"MS",x:4,o:3,t:"Toilette de fractura expuesta sin tratamiento óseo definitivo."},
  {c:"MS.04.04",r:"MS",x:4,o:4,t:"Cupulectomía radial."},
  {c:"MS.04.05",r:"MS",x:4,o:5,t:"Drenaje de infección o absceso profundo."},
  {c:"MS.04.06",r:"MS",x:4,o:6,t:"Extracción de material de osteosíntesis (placas, tornillos, etc.). Excluye la extracción de clavijas. En caso de ser mas de una extracción, se debe aplicar las normas primarias."},
  {c:"MS.04.07",r:"MS",x:4,o:7,t:"Tratamiento quirúrgico de una osteomielitis de un metacarpiano o una falange."},
  {c:"MS.04.08",r:"MS",x:4,o:8,t:"Tratamiento quirúrgico de una artritis u osteoartritis séptica de una articulación: radiocubital inferior, radiocarpiana, intercarpiana, carpometacarpiana, metacarpofalángica o interfalángica."},
  {c:"MS.04.09",r:"MS",x:4,o:9,t:"Resección ósea por osteomielitis."},
  {c:"MS.04.10",r:"MS",x:4,o:10,t:"Artrodesis interfalángica proximal o distal."},
  {c:"MS.04.11",r:"MS",x:4,o:11,t:"Artrodesis metacarpofalángica de los dedos y del pulgar."},
  {c:"MS.04.12",r:"MS",x:4,o:12,t:"Amputaciones de un rayo Completo (dedo más metacarpiano)"},
  {c:"MS.04.13",r:"MS",x:4,o:13,t:"Liberación articular en mano (hasta 2 articulaciones), interfalángica, metacarpofalángica y muñeca."},
  {c:"MS.04.14",r:"MS",x:4,o:14,t:"Reducción abierta de luxación irreductible metacarpofalángica o interfalángica de los dedos."},
  {c:"MS.04.15",r:"MS",x:4,o:15,t:"Extirpación (a cielo abierto o por artroscopía) de un ganglión de la cara palmar o dorsal de la muñeca"},
  {c:"MS.04.16",r:"MS",x:4,o:16,t:"Tratamiento quirúrgico (a cielo abierto o endoscópico) de las neuropatías compresivas del MS: síndrome del túnel carpiano con tenosinovectomía de los tendones flexores o sin ella, síndrome del canal de Guyon, neurodoscitis cubital con transposición del cubital o sin ella, síndrome del nervio interóseo anterior o posterior, del pronador redondo, síndrome de Wartenberg, síndrome del espacio cuadrilátero supraescapular, infraespinoso, etc."},
  {c:"MS.04.17",r:"MS",x:4,o:17,t:"Reparación ligamentaria en articulación metacarpofalángica del pulgar y muñeca o codo"},
  {c:"MS.04.18",r:"MS",x:4,o:18,t:"Reparación de lesiones ligamentarias agudas o inveteradas de las articulaciones metacarpofalángica o interfalángica"},
  {c:"MS.04.19",r:"MS",x:4,o:19,t:"Miectomía, miotomía, desinserción, descenso, alargamiento o acortamiento de una o más unidades musculotendinosas"},
  {c:"MS.04.20",r:"MS",x:4,o:20,t:"Colocación de una prótesis tendinosa temporaria (incluye tenorrafia en asa del músculo flexor superficial con el profundo)"},
  {c:"MS.04.21",r:"MS",x:4,o:21,t:"Tenodesis de un tendón flexor o extensor en el antebrazo, la muñeca, la mano o un dedo"},
  {c:"MS.04.22",r:"MS",x:4,o:22,t:"Tenosinovectomía radical en la cara palmar o dorsal de la muñeca o la mano. Tenosinovectomía radical digital"},
  {c:"MS.04.23",r:"MS",x:4,o:23,t:"Tratamiento quirúrgico de una tenosinovitis crónica estenosante (enfermedad de De Quervain, dedos o pulgar “en gatillo”, etc.) por medio de la sección de la polea tendinosa. Incluye eventual tenosinovectomía o tenólisis local. Resección de quiste de un tendón flexor. Más de dos dedos con patología agregar 30% al código de la complejidad."},
  {c:"MS.04.24",r:"MS",x:4,o:24,t:"Tratamiento quirúrgico de un seudoneuroma traumático o “de amputación” de un nervio o rama nerviosa (extirpación, transposición, etc.)"},
  {c:"MS.04.25",r:"MS",x:4,o:25,t:"Corrección de una sindactilia cicatrizal por medio de zetaplastia (única 0 múltiple) o con colgajos locales o injertos de piel (parcial o total)"},
  {c:"MS.04.26",r:"MS",x:4,o:26,t:"Colgajo fileteado de un dedo. Incluye la resección de las falanges"},
  {c:"MS.04.27",r:"MS",x:4,o:27,t:"Reparación de un pulpejo con injertos de piel parcial o total, con colgajos de vecindad (técnicas de Atasoy, Kuttler, Moberg, etc.) con un colgajo cruzado de dedo (cross-finger flap). Incluye el cierre del lecho dador con injerto o sin él"},
  {c:"MS.04.28",r:"MS",x:4,o:28,t:"Tallado y aplicación de un colgajo rotatorio de vecindad. Incluye tratamiento de la zona dadora"},
  {c:"MS.04.29",r:"MS",x:4,o:29,t:"Biopsia a cielo abierto. Biopsia guiada por imágenes por causa oncológica."},
  {c:"MS.04.30",r:"MS",x:4,o:30,t:"Extirpación de una lesión tumoral o seudotumoral benigna y localizada de partes blandas, que no engloba ni infiltra estructuras profundas vecinas (quiste epidermoide, lipoma localizado, hemangioma localizado, bursitis retroolecraneana u otros tumores similares)"},
  {c:"MS.04.31",r:"MS",x:4,o:31,t:"Tumores de partes blandas, de menos de 3 cm."},
  {c:"MS.04.32",r:"MS",x:4,o:32,t:"Tratamiento radical de un tumor maligno de piel sin invasión de estructuras profundas"},
  {c:"MS.04.33",r:"MS",x:4,o:33,t:"Extirpación de un tumor glómico subungueal."},
  {c:"MS.04.34",r:"MS",x:4,o:34,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, 5 o más grupos musculares o más, unilateral o bilateral."},
  {c:"MS.05.01",r:"MS",x:5,o:1,t:"Fractura expuesta de mano. Tratamiento completo, incluye osteodesis de metacarpianos y falanges (más de 2 osteodesis agregar 30%)"},
  {c:"MS.05.02",r:"MS",x:5,o:2,t:"Fractura de clavícula. Reducción y osteosíntesis."},
  {c:"MS.05.03",r:"MS",x:5,o:3,t:"Fractura de un hueso del carpo (escafoides, grande, etc.). Reducción abierta y osteosíntesis"},
  {c:"MS.05.04",r:"MS",x:5,o:4,t:"Fractura diafisaria de radio o cúbito. Reducción y osteosíntesis."},
  {c:"MS.05.05",r:"MS",x:5,o:5,t:"Fracturas de olécranon. Reducción y osteosíntesis."},
  {c:"MS.05.06",r:"MS",x:5,o:6,t:"Liberación articular de codo u hombro a cielo abierto."},
  {c:"MS.05.07",r:"MS",x:5,o:7,t:"Reducción a cielo abierto de luxación irreductible de hombro/codo."},
  {c:"MS.05.08",r:"MS",x:5,o:8,t:"Tratamiento quirúrgico de una artritis u osteoartritis séptica del hombro o el codo"},
  {c:"MS.05.09",r:"MS",x:5,o:9,t:"Síndrome del túnel carpiano complejo (recidivado) o recidiva de cualquier otra neuropatía compresiva."},
  {c:"MS.05.10",r:"MS",x:5,o:10,t:"Reconstrucción del complejo fibro-cartílago triangular."},
  {c:"MS.05.11",r:"MS",x:5,o:11,t:"Tenorrafia de uno o más Tendones extensores en el antebrazo, la muñeca o la mano. (Más de 2 tendones, agregar un 30% al valor de dicha complejidad)"},
  {c:"MS.05.12",r:"MS",x:5,o:12,t:"Extirpación de un ganglión del hombro o en el codo."},
  {c:"MS.05.13",r:"MS",x:5,o:13,t:"Artroplastia por resección esternoclavicular (abierta o artroscópica)"},
  {c:"MS.05.14",r:"MS",x:5,o:14,t:"Artroplastia-resección trapecio- metacarpiana."},
  {c:"MS.05.15",r:"MS",x:5,o:15,t:"Artroplastia radiocubital distal (Darrach, Bowers, Sauvé- Kapandji, etc.)"},
  {c:"MS.05.16",r:"MS",x:5,o:16,t:"Seudoartrosis de metacarpiano o falanges."},
  {c:"MS.05.17",r:"MS",x:5,o:17,t:"Resección de un hueso del carpo"},
  {c:"MS.05.18",r:"MS",x:5,o:18,t:"Artrodesis carpometacarpiana del pulgar o los dedos"},
  {c:"MS.05.19",r:"MS",x:5,o:19,t:"Artrólisis metacarpofalángica o interfalángica"},
  {c:"MS.05.20",r:"MS",x:5,o:20,t:"Sección de tendones flexores en 1 dedo, o su equivalente (es decir, hasta 2 tendones) en la palma de la mano o el antebrazo"},
  {c:"MS.05.21",r:"MS",x:5,o:21,t:"Transferencia tendinosa para sección de extensores."},
  {c:"MS.05.22",r:"MS",x:5,o:22,t:"Transferencias tendinosas o musculotendinosas para reparar la oposición del pulgar."},
  {c:"MS.05.23",r:"MS",x:5,o:23,t:"Tenoplastia del aparato extensor en el dorso de un dedo para corrección de deformaciones digitales (Mallet finger, boutonniére, cuello de cisne, enfermedades neuroortopedicas, etc.)"},
  {c:"MS.05.24",r:"MS",x:5,o:24,t:"Neurorrafia de colaterales nerviosos en dedos o palma de la mano. (Más de 2, agregar un 30% al valor de dicha complejidad)"},
  {c:"MS.05.25",r:"MS",x:5,o:25,t:"Reconstrucción de una polea tendinosa por medio de un injerto de tendón."},
  {c:"MS.05.26",r:"MS",x:5,o:26,t:"Polidactilia simple. (Dos o más dedos, agregar un 30% al valor de dicha complejidad)"},
  {c:"MS.05.27",r:"MS",x:5,o:27,t:"Síndrome de bandas amnióticas (anular grooves) o electrodactilias."},
  {c:"MS.05.28",r:"MS",x:5,o:28,t:"Tratamiento del tortícolis congénito."},
  {c:"MS.05.29",r:"MS",x:5,o:29,t:"Extirpación de un tumor óseo benigno, sin reconstrucción (osteocondroma, tumores benignos periósticos y lesiones quísticas)"},
  {c:"MS.05.30",r:"MS",x:5,o:30,t:"Extirpación de una lesión tumoral o seudotumoral benigna y localizada de partes blandas, que engloba o infiltra estructuras profundas vecinas (lipoma racemoso, hemangioma, linfangioma, tumor de células gigantes de una vaina tenosinovial, xantoma sinovial, sinovitis vellonodularfascitis nodular seudosarcomatosa, tofo gotoso y lesiones similares)"},
  {c:"MS.05.31",r:"MS",x:5,o:31,t:"Tumores de partes blandas benignos mayores de 3 cm."},
  {c:"MS.05.32",r:"MS",x:5,o:32,t:"Resecciones acrales (muñeca y mano,) de tumores malignos de bajo grado o de grado intermedio de agresividad, o tumores benignos agresivos (recidivantes) de cualquier localización (superficiales o profundos)."},
  {c:"MS.05.33",r:"MS",x:5,o:33,t:"Procedimientos terapéuticos percutáneos guiados por imágenes (Tratamiento del quiste óseo, simple, termo-ablación percutánea, crio-ablación percutánea, alcoholización)"},
  {c:"MS.05.34",r:"MS",x:5,o:34,t:"Curetaje y relleno con injerto óseo de una lesión cavitaria en falanges, metacarpianos y carpo"},
  {c:"MS.06.01",r:"MS",x:6,o:1,t:"Fracturas expuestas de húmero y antebrazo. Tratamiento completo (toilette y fijación con tutor externo o estabilización interna) Fractura expuesta de mano/muñeca tratamiento de lesiones óseas + reparación de tendones."},
  {c:"MS.06.02",r:"MS",x:6,o:2,t:"Fracturas del radio distal metafisarias (incluye tratamiento del cubito distal) Reducción y osteosíntesis."},
  {c:"MS.06.03",r:"MS",x:6,o:3,t:"Fracturas de la apófisis coronoides. Reducción y osteosíntesis."},
  {c:"MS.06.04",r:"MS",x:6,o:4,t:"Fractura diafisarias de cúbito y radio. Fractura-luxación de Galeazzi, de Monteggia o de Essex-Lopresti. Reducción abierta y fijación interna de ambos huesos."},
  {c:"MS.06.05",r:"MS",x:6,o:5,t:"Fracturas de la diáfisis del húmero. Reducción y osteosíntesis."},
  {c:"MS.06.06",r:"MS",x:6,o:6,t:"Fracturas de humero proximal (extraarticulares) o supracondíleas de húmero o escápula extraarticular. Reducción y osteosíntesis."},
  {c:"MS.06.07",r:"MS",x:6,o:7,t:"Fracturas de la cúpula radial. Osteosíntesis o artroplastía."},
  {c:"MS.06.08",r:"MS",x:6,o:8,t:"Artroscopía simple de hombro (cuerpos libres, sinovectomías, capsulotomia)"},
  {c:"MS.06.09",r:"MS",x:6,o:9,t:"Artroscopía simple de muñeca y codo. Impingement de muñeca, Fracturas intraarticulares, sinovectomía, tratamiento endoscópico de la epicondilitis"},
  {c:"MS.06.10",r:"MS",x:6,o:10,t:"Reparación abierta o artroscópica de lesiones ligamentarias agudas de la muñeca o de la articulación radiocubital distal."},
  {c:"MS.06.11",r:"MS",x:6,o:11,t:"Artroplastia por resección, no protésica de codo. Con interposición de fascia lata, agregar un 30% al valor de dicha complejidad."},
  {c:"MS.06.12",r:"MS",x:6,o:12,t:"Artroplastia por resección acromioclavicular (Munford)"},
  {c:"MS.06.13",r:"MS",x:6,o:13,t:"Plástica ligamentaria de codo, con injerto."},
  {c:"MS.06.14",r:"MS",x:6,o:14,t:"Reparación /reinserción del tendón distal de bíceps en la tuberosidad bicipital del radio."},
  {c:"MS.06.15",r:"MS",x:6,o:15,t:"Seudoartrosis de clavícula"},
  {c:"MS.06.16",r:"MS",x:6,o:16,t:"Seudoartrosis de radio o cubito. Tratamiento del cúbito varo."},
  {c:"MS.06.17",r:"MS",x:6,o:17,t:"Osteotomía de húmero."},
  {c:"MS.06.18",r:"MS",x:6,o:18,t:"Amputación quirúrgica de brazo, codo, antebrazo, radiocarpiana, intercarpiana o carpometacarpiana y amputación de un dedo con su metacarpiano (amputación de un rayo digital)"},
  {c:"MS.06.19",r:"MS",x:6,o:19,t:"Tratamiento de la inestabilidad del carpo. Luxaciones del carpo. Incluye osteodesis."},
  {c:"MS.06.20",r:"MS",x:6,o:20,t:"Tratamiento de la Enfermedad de Kiemböck."},
  {c:"MS.06.21",r:"MS",x:6,o:21,t:"Reemplazo protésico en huesos del carpo."},
  {c:"MS.06.22",r:"MS",x:6,o:22,t:"Resección de la primera fila del carpo."},
  {c:"MS.06.23",r:"MS",x:6,o:23,t:"Osteoplastia (osteotomía con acortamiento, alargamiento o corrección de desejes, malas rotaciones o deformaciones óseas) en los huesos del carpo, los metacarpianos o las falanges."},
  {c:"MS.06.24",r:"MS",x:6,o:24,t:"Tratamiento quirúrgico de la necrosis aséptica de un hueso del carpo, con injerto óseo"},
  {c:"MS.06.25",r:"MS",x:6,o:25,t:"Reemplazo protésico en articulación metacarpofalángica o interfalángica"},
  {c:"MS.06.26",r:"MS",x:6,o:26,t:"Artrolisis de las articulaciones metacarpofalángicas de los cuatro dedos."},
  {c:"MS.06.27",r:"MS",x:6,o:27,t:"Tenólisis de extensores en mano."},
  {c:"MS.06.28",r:"MS",x:6,o:28,t:"Tenólisis de uno o más tendones flexores o extensores en el antebrazo o la muñeca o la palma. Procedimientos tendinosos múltiples: hasta tres distribuidos en un miembro."},
  {c:"MS.06.29",r:"MS",x:6,o:29,t:"Sección de tendones flexores en un dedo, o su equivalente (es decir, hasta 2 tendones) En la palma de la mano o el antebrazo, más colaterales nerviosos o vasculares."},
  {c:"MS.06.30",r:"MS",x:6,o:30,t:"Sección de tendones flexores en 2 dedos, o su equivalente (es decir, hasta 4 tendones) en la palma de la mano o el antebrazo."},
  {c:"MS.06.31",r:"MS",x:6,o:31,t:"Injerto de tendón flexor. (Dos o más tendones en diferentes dedos, agregar un 30% al valor de dicha complejidad)"},
  {c:"MS.06.32",r:"MS",x:6,o:32,t:"Transferencia tendinosa en parálisis simple de la mano. Hasta 2 tendones."},
  {c:"MS.06.33",r:"MS",x:6,o:33,t:"Tratamiento quirúrgico de los síndromes isquémicos del antebrazo (Volkmann) o la mano (Finochietto), agudos o subagudos. Incluye fasciotomía o fasciectomía descompresiva, miotomías o miectomías, neurólisis de los nervios mediano o cubital"},
  {c:"MS.06.34",r:"MS",x:6,o:34,t:"Camptodactilia o clinodactilia (por cada dedo corregido), hipoplasia del pulgar"},
  {c:"MS.06.35",r:"MS",x:6,o:35,t:"Corrección de una sindactilia congénita por medio de zetaplastia (única o múltiple), con colgajos locales o injertos de piel (parcial o total) por cada comisura corregida"},
  {c:"MS.06.36",r:"MS",x:6,o:36,t:"Tratamiento de la enfermedad de Dupuytren con retracción metacarpofalángica de un solo dedo. (Dos o más rayos, agregar un 30% al valor de dicha complejidad)"},
  {c:"MS.06.37",r:"MS",x:6,o:37,t:"Transposición del nervio cubital del codo más osteotomía epitroclear y reinserción de músculos epitrocleares"},
  {c:"MS.06.38",r:"MS",x:6,o:38,t:"Transposición simple de dedo de la mano."},
  {c:"MS.06.39",r:"MS",x:6,o:39,t:"Sinostosis radiocubital en el niño."},
  {c:"MS.06.40",r:"MS",x:6,o:40,t:"Sutura arterial o venosa (axila, brazo, codo)"},
  {c:"MS.06.41",r:"MS",x:6,o:41,t:"Exéresis de la costilla cervical"},
  {c:"MS.06.42",r:"MS",x:6,o:42,t:"Macrodactilia."},
  {c:"MS.06.43",r:"MS",x:6,o:43,t:"Braquidactilia."},
  {c:"MS.06.44",r:"MS",x:6,o:44,t:"Enclavado endomedular profiláctico en húmero."},
  {c:"MS.06.45",r:"MS",x:6,o:45,t:"Ampliaciones de márgenes en cirugía de tumores de bajo grado."},
  {c:"MS.06.46",r:"MS",x:6,o:46,t:"Curetaje y relleno con cemento (con o sin osteosíntesis) de una lesión metastásica en húmero."},
  {c:"MS.06.47",r:"MS",x:6,o:47,t:"Curetaje y relleno con injerto óseo de una lesión cavitaria benigna en radio, cúbito, húmero o escápula"},
  {c:"MS.07.01",r:"MS",x:7,o:1,t:"Fractura intraarticular de la cabeza humeral y supra-inter-transcondílea de paleta humeral o intraarticulares de escápula. Reducción y osteosíntesis."},
  {c:"MS.07.02",r:"MS",x:7,o:2,t:"Fracturas del radio distal intraaticular, con o sin fractura del cúbito distal, con o sin lesión del fibrocatílago triangular. Osteosíntesis del radio. Incluye tratamiento del cúbito distal o del fibrocartílago triangular."},
  {c:"MS.07.03",r:"MS",x:7,o:3,t:"Fractura expuesta de la mano (lesión grave de mano) Osteodesis de metacarpianos y/o Falanges + reparación tendinosa + sutura de nervios/vasos. Sutura de más de tres tendones o más de dos nervios o vasos agregar 30%."},
  {c:"MS.07.04",r:"MS",x:7,o:4,t:"Luxofracturas del carpo. Reducción abierta y fijación interna de uno o varios huesos. Incluye eventual reparación ligamentaria."},
  {c:"MS.07.05",r:"MS",x:7,o:5,t:"Seudoartrosis de húmero."},
  {c:"MS.07.06",r:"MS",x:7,o:6,t:"Seudoartrosis biósea de antebrazo."},
  {c:"MS.07.07",r:"MS",x:7,o:7,t:"Seudoartrosis del escafoides u otros huesos del carpo"},
  {c:"MS.07.08",r:"MS",x:7,o:8,t:"Reparación abierta o artroscópica del manguito rotador."},
  {c:"MS.07.09",r:"MS",x:7,o:9,t:"Inestabilidad glenohumeral. Reparación abierta o artroscópica"},
  {c:"MS.07.10",r:"MS",x:7,o:10,t:"Lesión SLAP, reparación artrocópica. Tenotomía o Tenodesis del bíceps artroscópica."},
  {c:"MS.07.11",r:"MS",x:7,o:11,t:"Plástica acromioclavicular abierta o artroscípica (incluye injertos)"},
  {c:"MS.07.12",r:"MS",x:7,o:12,t:"Reparación abierta o artroscópica de lesiones ligamentarias inveteradas de la muñeca o de la articulación radiocubital distal (plástica). Reparación de lesiones inveteradas"},
  {c:"MS.07.13",r:"MS",x:7,o:13,t:"Reemplazo parcial de hombro."},
  {c:"MS.07.14",r:"MS",x:7,o:14,t:"Reemplazo protésico del trapecio."},
  {c:"MS.07.15",r:"MS",x:7,o:15,t:"Extracción de prótesis de hombro, codo o muñeca. (sin colocación de espaciador)."},
  {c:"MS.07.16",r:"MS",x:7,o:16,t:"Artroplastia-resección de las articulaciones metacarpofalángicas de los cuatro dedos."},
  {c:"MS.07.17",r:"MS",x:7,o:17,t:"Artroplastia-resección y tenosuspensión de la articulación trapecio-metacarpiana."},
  {c:"MS.07.18",r:"MS",x:7,o:18,t:"Artrodesis de hombro o codo."},
  {c:"MS.07.19",r:"MS",x:7,o:19,t:"Artrodesis radiocarpianas parciales o intercarpianas."},
  {c:"MS.07.20",r:"MS",x:7,o:20,t:"Artrodesis total de la muñeca."},
  {c:"MS.07.21",r:"MS",x:7,o:21,t:"Inestabilidad esternoclavicular aguda o crónica."},
  {c:"MS.07.22",r:"MS",x:7,o:22,t:"Osteoplastia (osteotomía con acortamiento, alargamiento o corrección de desejes óseos, malas rotaciones o deformaciones óseas) en la clavícula, el húmero, el radio o el cúbito"},
  {c:"MS.07.23",r:"MS",x:7,o:23,t:"Tratamiento quirúrgico de la osteomielitis de la escápula, el húmero, el radio, el cúbito. Incluye saucerización."},
  {c:"MS.07.24",r:"MS",x:7,o:24,t:"Tenoplastía (injerto o transferencia) de un tendón flexor o extensor, o más de uno, en el antebrazo, la muñeca o la palma."},
  {c:"MS.07.25",r:"MS",x:7,o:25,t:"Injerto de los tendones flexores en un dedo (técnica de Kleinert o injerto tendinoso)"},
  {c:"MS.07.26",r:"MS",x:7,o:26,t:"Transferencias tendinosas o musculotendinosas para la corrección de la parálisis alta del mediano, parálisis radial, parálisis cubital, o parálisis de la flexión o extensión del codo (con tríceps, bíceps u operación de Steindler)"},
  {c:"MS.07.27",r:"MS",x:7,o:27,t:"Tratamiento quirúrgico de las secuelas tardías de los síndromes isquémicos del antebrazo (Volkmann) o la mano (Finochietto). Incluye miotomías, miectomías, neurólisis de los nervios mediano o cubital y transferencias tendinosas múltiples."},
  {c:"MS.07.28",r:"MS",x:7,o:28,t:"Tallado y aplicación de un colgajo cutáneo abdominal, torácico braquial o antebraquial"},
  {c:"MS.07.29",r:"MS",x:7,o:29,t:"Endoneurólisis interfascicular de un nervio o rama nerviosa."},
  {c:"MS.07.30",r:"MS",x:7,o:30,t:"Neurorrafia epineural o fascicular de un nervio o rama nerviosa."},
  {c:"MS.07.31",r:"MS",x:7,o:31,t:"Simpaticectomía periarterial en la mano o los dedos. Adventiciectomía con técnicas microquirúrgicas."},
  {c:"MS.07.32",r:"MS",x:7,o:32,t:"Revisión de suturas arteriales o venosas."},
  {c:"MS.07.33",r:"MS",x:7,o:33,t:"Corrección de la ráfaga cubital de los cuatro dedos con procedimientos sobre las partes blandas de las articulaciones metacarpofalángicas."},
  {c:"MS.07.34",r:"MS",x:7,o:34,t:"Tratamiento de la enfermedad de Dupuytren, con retracción de la articulación interfalángica proximal de un dedo o más de uno, o con retracción metacarpofalángica, de más de un dedo (incluye eventual artrólisis, zetaplastia única o múltiple, injertos de piel parcial o total, etc.)."},
  {c:"MS.07.35",r:"MS",x:7,o:35,t:"Mano hendida."},
  {c:"MS.07.36",r:"MS",x:7,o:36,t:"Tratamiento quirúrgico de elevación congénita de la escápula."},
  {c:"MS.07.37",r:"MS",x:7,o:37,t:"Tratamiento quirúrgico de la lesión de Monteggia inveterada y de la luxación congénita de la cabeza del radio."},
  {c:"MS.07.38",r:"MS",x:7,o:38,t:"Tratamiento quirúrgico de la enfermedad por bridas amnióticas proximal a la mano."},
  {c:"MS.07.39",r:"MS",x:7,o:39,t:"Reconstrucción del pulgar."},
  {c:"MS.08.01",r:"MS",x:8,o:1,t:"Fractura de la escápula con compromiso de la cavidad glenoidea. Reducción abierta y fijación interna."},
  {c:"MS.08.02",r:"MS",x:8,o:2,t:"Cirugía de revisión del manguito rotador o revisión de la inestabilidad del hombro. (abierta o artroscópica)"},
  {c:"MS.08.03",r:"MS",x:8,o:3,t:"Artroplastia total de hombro."},
  {c:"MS.08.04",r:"MS",x:8,o:4,t:"Reemplazo protésico de muñeca o codo."},
  {c:"MS.08.05",r:"MS",x:8,o:5,t:"Reemplazo protésico de las cuatro articulaciones metacarpofalángicas"},
  {c:"MS.08.06",r:"MS",x:8,o:6,t:"Reconstrucción del manguito rotador del hombro con transferencias tendinosas (abierto o atroscópico)."},
  {c:"MS.08.07",r:"MS",x:8,o:7,t:"Amputación quirúrgica o desarticulación a nivel del hombro."},
  {c:"MS.08.08",r:"MS",x:8,o:8,t:"Sección de tendones flexores en 3 o más dedos, o su equivalente (es decir, 6 o más tendones) en la palma de la mano o el antebrazo, más colaterales nerviosos."},
  {c:"MS.08.09",r:"MS",x:8,o:9,t:"Reparación de un nervio o una rama nerviosa con injertos nerviosos."},
  {c:"MS.08.10",r:"MS",x:8,o:10,t:"Reparación arteriovenosa (parche, reemplazo o bypass), aneurismas, seudoaneurismas, fístulas arteriovenosas. Injerto de vena."},
  {c:"MS.08.11",r:"MS",x:8,o:11,t:"Tromboendarterectomía con arterioplastia simultánea o sin ella."},
  {c:"MS.08.12",r:"MS",x:8,o:12,t:"Resección de un aneurisma, seudoaneurisma o fístula arteriovenosa y reparación arterial con injerto de vena (parche, reemplazo o bypass)."},
  {c:"MS.08.13",r:"MS",x:8,o:13,t:"Transferencias tendinosas o musculotendinosas para la corrección de parálisis combinadas, parálisis cerebral, cuadriplejías o parálisis obstétricas del plexo braquial."},
  {c:"MS.08.14",r:"MS",x:8,o:14,t:"Liberación de retracción de la 1ªcomisura. Incluye los procedimientos de reparación de la cobertura cutánea, excepto los colgajos libres."},
  {c:"MS.08.15",r:"MS",x:8,o:15,t:"Extirpación de un tumor neurogénico benigno de un nervio o rama nerviosa y reparación con injertos nerviosos."},
  {c:"MS.08.16",r:"MS",x:8,o:16,t:"Tratamiento quirúrgico de la agenesia del radio o del cúbito."},
  {c:"MS.08.17",r:"MS",x:8,o:17,t:"Deformidad de Sprengel."},
  {c:"MS.08.18",r:"MS",x:8,o:18,t:"Toma y aplicación de un colgajo, en isla con pedículo o neurovascular (island-flap). Incluye el cierre del lecho dador con un injerto de piel."},
  {c:"MS.08.19",r:"MS",x:8,o:19,t:"Reemplazo articular de pie a mano no vascularizado."},
  {c:"MS.08.20",r:"MS",x:8,o:20,t:"Pulgarización del índice."},
  {c:"MS.08.21",r:"MS",x:8,o:21,t:"Neurorrafia en lesiones del plexo braquial."},
  {c:"MS.08.22",r:"MS",x:8,o:22,t:"Extirpación radical de un tumor maligno de piel con invasión de estructuras profundas sin cobertura cutánea."},
  {c:"MS.08.23",r:"MS",x:8,o:23,t:"Tratamiento radical de un tumor maligno de la sinovial de una articulación."},
  {c:"MS.08.24",r:"MS",x:8,o:24,t:"Resecciones proximales del miembro superior de tumores de alto grado incluyendo la cintura escapular. Compromiso de más de un compartimento muscular."},
  {c:"MS.08.25",r:"MS",x:8,o:25,t:"Curetajes y rellenos por lesiones óseas benignas agresivas en cúbito, radio o húmero (Ejemplo TCG)"},
  {c:"MS.08.26",r:"MS",x:8,o:26,t:"Ampliaciones de márgenes en cirugía de tumores de alto grado."},
  {c:"MS.08.27",r:"MS",x:8,o:27,t:"Procedimientos óseos multinivel en neuroortopedia: dos niveles distribuidos en un miembro; incluye todos los procedimientos tendinosos necesarios en cualquier nivel (niveles MI: 1-escapula, 2-hombro/humero proximal, 3-codo/humero distal, 4-antebrazo distal/muñeca y 5-mano; PC: región equivalente de MI)."},
  {c:"MS.09.01",r:"MS",x:9,o:1,t:"Revisión de artroplastia protésica de hombro, codo o muñeca en un tiempo."},
  {c:"MS.09.02",r:"MS",x:9,o:2,t:"Primer tiempo de revisión de revisión total de hombro, codo o muñeca infectado o no, más espaciador."},
  {c:"MS.09.03",r:"MS",x:9,o:3,t:"Segundo tiempo de reimplante de reemplazo total de hombro, codo o muñeca infectado."},
  {c:"MS.09.04",r:"MS",x:9,o:4,t:"Reconstrucción del pulgar (en casos traumáticos o por malformaciones congénitas) por transposición de un dedo de la mano, con sus pedículos neurovasculares (pulgarización)"},
  {c:"MS.09.05",r:"MS",x:9,o:5,t:"Sección de tendones flexores en 3 o más dedos, o su equivalente (es decir, 6 o más tendones) en la palma de la mano o el antebrazo, más colaterales nerviosos y vascular. (Revascularización)."},
  {c:"MS.09.06",r:"MS",x:9,o:6,t:"Tratamiento quirúrgico de los seudoneuromas traumáticos o “de amputación” del plexo braquial."},
  {c:"MS.09.07",r:"MS",x:9,o:7,t:"Tratamiento quirúrgico de los síndromes neurovasculares compresivos cervicobraquiales, sindrome del opérculo torácico nervioso y/o vascular."},
  {c:"MS.09.08",r:"MS",x:9,o:8,t:"Reparación de un nervio o una rama nerviosa con neurotización."},
  {c:"MS.09.09",r:"MS",x:9,o:9,t:"Reimplante de un dedo."},
  {c:"MS.09.10",r:"MS",x:9,o:10,t:"Injertos articulares vascularizados."},
  {c:"MS.09.11",r:"MS",x:9,o:11,t:"Suspensión escapulotorácica, de tipo Eden-Lange."},
  {c:"MS.09.12",r:"MS",x:9,o:12,t:"Fusión escapulotorácica."},
  {c:"MS.09.13",r:"MS",x:9,o:13,t:"Extirpación radical de un tumor maligno de las partes blandas más plásticas asociadas reconstructivas."},
  {c:"MS.09.14",r:"MS",x:9,o:14,t:"Procedimientos óseos multinivel en neuroortopedia: tres niveles distribuidos en un miembro; incluye todos los procedimientos tendinosos necesarios en cualquier nivel (niveles MI: 1-escapula, 2-hombro/humero proximal, 3-codo/humero distal, 4-antebrazo distal/muñeca y 5-mano; PC: región equivalente de MI)."},
  {c:"MS.10.01",r:"MS",x:10,o:1,t:"Revisión de un reemplazo total de hombro, más reconstrucción con injerto óseo de Banco de Tejidos."},
  {c:"MS.10.02",r:"MS",x:10,o:2,t:"Transferencias de un dedo del pie a la mano."},
  {c:"MS.10.03",r:"MS",x:10,o:3,t:"Amputación interescapulotorácica."},
  {c:"MS.10.04",r:"MS",x:10,o:4,t:"Reparación del plexo braquial con injertos nerviosos o neurotización."},
  {c:"MS.10.05",r:"MS",x:10,o:5,t:"Neurólisis del plexo braquial en lesiones traumáticas o en plexitis actínicas"},
  {c:"MS.10.06",r:"MS",x:10,o:6,t:"Reconstrucción del pulgar u otro dedo de la mano (en casos traumáticos o por malformaciones congénitas) por medio de un trasplante autólogo de un dedo de la mano o del pie, con anastomosis vasculares microquirúrgicas y neurorrafias."},
  {c:"MS.10.07",r:"MS",x:10,o:7,t:"Transferencia libre (bipolar) de una unidad musculotendinosa, con sutura microquirúrgica de su pedículo neurovascular, en hombro, brazo, antebrazo, muñeca o mano."},
  {c:"MS.10.08",r:"MS",x:10,o:8,t:"Toma y aplicación de un injerto óseo vascularizado con microanastomosis vasculares. Incluye la preparación del lecho receptor y el tratamiento del lecho dador"},
  {c:"MS.10.09",r:"MS",x:10,o:9,t:"Extirpación de un tumor neurogénico del plexo braquial y reparación de una o más raíces o troncos con injertos nerviosos."},
  {c:"MS.10.10",r:"MS",x:10,o:10,t:"Reimplante de un MS a nivel del hombro, brazo, codo, antebrazo, muñeca, mano, transmetacarpiano, o de 2 o más dedos."},
  {c:"MS.10.11",r:"MS",x:10,o:11,t:"Toma y aplicación de un colgajo cutáneo con anastomosis arterial y venosa en el lecho receptor (free-flap). Incluye las microanastomosis vasculares y el cierre del lecho dador."},
  {c:"MS.10.12",r:"MS",x:10,o:12,t:"Tratamiento de tumor óseo maligno con reconstrucción completa."},
  {c:"MS.10.13",r:"MS",x:10,o:13,t:"Resección ósea tumoral segmentaria. Tratamiento de tumores malignos (primarios o secundarios) o benignos agresivos (en bloque) más reconstrucción de cualquier tipo (endoprótesis, aloprótesis, injerto óseo masivo, espaciador de cemento, peroné vascularizado, etc.)"},
  {c:"PC.01.01",r:"PC",x:1,o:1,t:"Infiltraciones. Artrocentesis."},
  {c:"PC.01.02",r:"PC",x:1,o:2,t:"Sutura de herida simple, no quirúrgica."},
  {c:"PC.01.03",r:"PC",x:1,o:3,t:"Evaluación bajo radioscopia en quirófano."},
  {c:"PC.01.04",r:"PC",x:1,o:4,t:"Artrografía o artroneumografía por punción, en medio quirúrgico y con intensificador de imágenes."},
  {c:"PC.02.01",r:"PC",x:2,o:1,t:"Reducción de fracturas de pelvis o fémur. Incluye cincha pelviana o tracción esquelética como tratamiento definitivo. Calzón de yeso."},
  {c:"PC.02.02",r:"PC",x:2,o:2,t:"Tracciones esqueléticas."},
  {c:"PC.02.03",r:"PC",x:2,o:3,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, hasta 4 grupos musculares, unilateral o bilateral."},
  {c:"PC.03.01",r:"PC",x:3,o:1,t:"Reducción de luxación de reemplazo total de cadera o reemplazo parcial de cadera, con anestesia, con yeso o sin él."},
  {c:"PC.03.02",r:"PC",x:3,o:2,t:"Miorrafias."},
  {c:"PC.03.03",r:"PC",x:3,o:3,t:"Fasciotomías."},
  {c:"PC.03.04",r:"PC",x:3,o:4,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, 5 grupos musculares, o más, unilateral o bilateral."},
  {c:"PC.03.05",r:"PC",x:3,o:5,t:"Punción biopsia."},
  {c:"PC.04.01",r:"PC",x:4,o:1,t:"Extracción de material de osteosíntesis."},
  {c:"PC.04.02",r:"PC",x:4,o:2,t:"Tratamiento de la fractura expuesta de fémur, sin tratamiento óseo definitivo ni colocación de tutor."},
  {c:"PC.04.03",r:"PC",x:4,o:3,t:"Tratamiento incruento de la luxación congénita de cadera (Petit). Incluye tenotomía de aductores e inmovilización enyesada."},
  {c:"PC.04.04",r:"PC",x:4,o:4,t:"Resección de tumores de partes blandas extraaponeuróticos o superficiales menores de 3 cm."},
  {c:"PC.04.05",r:"PC",x:4,o:5,t:"Biopsia a cielo abierto. Biopsia guiada por imágenes por causa oncológica."},
  {c:"PC.04.06",r:"PC",x:4,o:6,t:"Toilette quirúrgica de osteosíntesis con conservación de implante y toma de biopsia."},
  {c:"PC.05.01",r:"PC",x:5,o:1,t:"Tratamiento con tutor externo de fractura de fémur como único procedimiento."},
  {c:"PC.05.02",r:"PC",x:5,o:2,t:"Tratamiento con tutor externo de fractura de pelvis inestable. Packing preperitoneal para pelvis hemodinamicamente inestable. Toilette quirúrgica de fractura expuesta de pelvis como único procedimiento."},
  {c:"PC.05.03",r:"PC",x:5,o:3,t:"Tratamiento del foco osteomielítico: secuestrectomía, curetaje. Extracción de cuerpo extraño en hueso, incluido material de osteosíntesis."},
  {c:"PC.05.04",r:"PC",x:5,o:4,t:"Tratamiento quirúrgico de ramas del plexo lumbosacro: exploración, neurorrafia."},
  {c:"PC.05.05",r:"PC",x:5,o:5,t:"Sinovectomía de cadera."},
  {c:"PC.05.06",r:"PC",x:5,o:6,t:"Toilette de reemplazo total de cadera infectado, sin retiro de prótesis."},
  {c:"PC.05.07",r:"PC",x:5,o:7,t:"Forage de cadera simple."},
  {c:"PC.05.08",r:"PC",x:5,o:8,t:"Reducción abierta de luxación irreductible de cadera o reemplazo total de cadera"},
  {c:"PC.05.09",r:"PC",x:5,o:9,t:"Artrotomía de cadera. Drenaje quirúrgico de Artritis séptica de cadera"},
  {c:"PC.05.10",r:"PC",x:5,o:10,t:"Reducción incruenta gradual de la LCC por método de Somerville"},
  {c:"PC.05.11",r:"PC",x:5,o:11,t:"Extracción de tumor de partes blandas subaponeuróticos, con más de 3 cm, no agresivos localmente."},
  {c:"PC.05.12",r:"PC",x:5,o:12,t:"Resección de un tumor óseo benigno, sin reconstrucción (osteocondroma, tumores benignos periósticos, lesiones quísticas)"},
  {c:"PC.05.13",r:"PC",x:5,o:13,t:"Procedimientos terapéuticos percutáneos guiados por imágenes (Tratamiento del quiste óseo, simple, termo-ablación percutánea, crio-ablación percutánea, alcoholización)"},
  {c:"PC.06.01",r:"PC",x:6,o:1,t:"Fractura diafisaria de fémur (excepto cadera) Reducción y osteosíntesis. Fractura expuesta de fémur (toilette y fijación con tutor externo). Fractura unicondilea de fémur, Reducción y osteosíntesis."},
  {c:"PC.06.02",r:"PC",x:6,o:2,t:"Fractura de ala ilíaca o rama pubiana. Reducción y osteosíntesis. Fractura expuesta de pelvis (toilette y fijación con tutor externo)"},
  {c:"PC.06.03",r:"PC",x:6,o:3,t:"Artroscopía diagnóstica, extracción de cuerpos libres, lavado articular, sinovectomía artroscópica, cadera en resorte, bursectomía."},
  {c:"PC.06.04",r:"PC",x:6,o:4,t:"Artrólisis de cadera. Queilectomía."},
  {c:"PC.06.05",r:"PC",x:6,o:5,t:"Forage de cadera simple más injerto óseo autólogo."},
  {c:"PC.06.06",r:"PC",x:6,o:6,t:"Amputación suprarrotuliana."},
  {c:"PC.06.07",r:"PC",x:6,o:7,t:"Toilette quirúrgica de osteosíntesis con retiro de implante y estabilización ósea no definitiva (tutor externo) osteomielitis. Toilette de osteomielitis y colocación de espaciador de cemento."},
  {c:"PC.06.08",r:"PC",x:6,o:8,t:"Cuadriceplastía a lo Judet."},
  {c:"PC.06.09",r:"PC",x:6,o:9,t:"Enclavado endomedular profiláctico en fémur."},
  {c:"PC.06.10",r:"PC",x:6,o:10,t:"Ampliaciones de márgenes en cirugías de tumores de bajo grado."},
  {c:"PC.06.11",r:"PC",x:6,o:11,t:"Curetaje y relleno con cemento (con o sin osteosíntesis) de una lesión metastásica en fémur."},
  {c:"PC.06.12",r:"PC",x:6,o:12,t:"Curetaje y relleno con injerto óseo de una lesión cavitaria benigna en fémur o tibia."},
  {c:"PC.07.01",r:"PC",x:7,o:1,t:"Fractura de cadera o subtrocantérica. Fractura supracondílea/intercondílea de fémur. Reducción y osteosíntesis."},
  {c:"PC.07.02",r:"PC",x:7,o:2,t:"Luxofracturas de pelvis extraarticulares. Reducción y osteosíntesis."},
  {c:"PC.07.03",r:"PC",x:7,o:3,t:"Osteotomía diafisarias de fémur. Osteotomías de fémur para correcciones angulares y rotacionales"},
  {c:"PC.07.04",r:"PC",x:7,o:4,t:"Reemplazo parcial de cadera."},
  {c:"PC.07.05",r:"PC",x:7,o:5,t:"Extracción de prótesis de cadera. Girdlestone."},
  {c:"PC.07.06",r:"PC",x:7,o:6,t:"Tratamiento artroscópico del pinzamiento fémoro-acetabular (incluye reparación labral con suturas) y/o combinación con patología extra articular (bursectomía, cadera en resorte interna o externa)"},
  {c:"PC.07.07",r:"PC",x:7,o:7,t:"Seudoartrosis fémur (diafisaria). Seudoartrosis séptica. Extracción de material, toilette y osteosíntesis con clavo recubierto/espaciador artesanal o placa recubierta de cemento y ATB."},
  {c:"PC.07.08",r:"PC",x:7,o:8,t:"Toilette quirúrgica de osteosíntesis de fémur con retiro de implante y estabilización ósea definitiva con otro implante."},
  {c:"PC.07.09",r:"PC",x:7,o:9,t:"Alargamientos óseos. Tratamiento quirúrgico de una deformidad angular mediante técnica de hemiepifisiodesis en más de un nivel o bilateral (modulación fisaria)"},
  {c:"PC.07.10",r:"PC",x:7,o:10,t:"Epifisiólisis de la cadera. Tratamiento quirúrgico."},
  {c:"PC.07.11",r:"PC",x:7,o:11,t:"Injerto nervioso de ramas terminales del plexo lumbosacro."},
  {c:"PC.07.12",r:"PC",x:7,o:12,t:"Tratamiento quirúrgico de la osteomielitis crónica de fémur mediante saucerización."},
  {c:"PC.08.01",r:"PC",x:8,o:1,t:"Fractura de acetábulo. Reducción y osteosíntesis del macizo acetabular por única vía u osteosíntesis del arco anterior o posterior pelviano"},
  {c:"PC.08.02",r:"PC",x:8,o:2,t:"Fractura periprotésica de cadera, sin recambio protésico"},
  {c:"PC.08.03",r:"PC",x:8,o:3,t:"Artroplastia total de cadera"},
  {c:"PC.08.04",r:"PC",x:8,o:4,t:"Revisiones de artroscopías de cadera, reconstrucción labral con injerto."},
  {c:"PC.08.05",r:"PC",x:8,o:5,t:"Artrodesis de cadera."},
  {c:"PC.08.06",r:"PC",x:8,o:6,t:"Desarticulación."},
  {c:"PC.08.07",r:"PC",x:8,o:7,t:"Osteotomías de pelvis. Osteotomía de cadera o fémur distal (supracondílea). Corrección de consolidación viciosa intraarticular o seudoartrosis intraarticular en fémur."},
  {c:"PC.08.08",r:"PC",x:8,o:8,t:"Tratamiento de la seudoartrosis de fémur proximal o fémur distal. Incluye utilización de más de un abordaje."},
  {c:"PC.08.09",r:"PC",x:8,o:9,t:"Epifisiolisis de la cadera del adolescente. Tratamiento quirúrgico mediante luxación controlada de la cadera más osteotomía."},
  {c:"PC.08.10",r:"PC",x:8,o:10,t:"Tratamiento quirúrgico de la luxación congénita de cadera (descenso, reducción, capsulotomía más plástica capsular más osteotomía)"},
  {c:"PC.08.11",r:"PC",x:8,o:11,t:"Luxación neurológica de la cadera. Tratamiento quirúrgico."},
  {c:"PC.08.12",r:"PC",x:8,o:12,t:"Tratamiento quirúrgico de una discrepancia de longitud mediante alargamiento óseo radual (osteogénesis en distracción con tutor externo) o de un defecto óseo mediante transporte óseo, hasta 5 centímetros."},
  {c:"PC.08.13",r:"PC",x:8,o:13,t:"Colgajos pediculados en isla, fasciocutáneos o musculares. Incluye injerto de piel en zona dadora."},
  {c:"PC.08.14",r:"PC",x:8,o:14,t:"Tumor benigno de partes blandas subaponeurótico, de más de 3 cm., agresivo localmente (p. ej., fibromatosis agresiva)"},
  {c:"PC.08.15",r:"PC",x:8,o:15,t:"Resección oncológica de tumor que comprometa un compartimiento anatómico, sin reconstrucción con injerto."},
  {c:"PC.08.16",r:"PC",x:8,o:16,t:"Ampliaciones de márgenes en cirugía de tumores de alto grado en fémur."},
  {c:"PC.08.17",r:"PC",x:8,o:17,t:"Procedimientos óseos multinivel: dos niveles distribuidos en uno o ambos miembros; incluye todos los procedimientos tendinosos necesarios en cualquier nivel (niveles MI: 1- pelvis, 2- cadera/fémur proximal, 3-rodilla/fémur distal, 4-pierna distal/tobillo y 5-pie; MS: región equivalente de MI)"},
  {c:"PC.09.01",r:"PC",x:9,o:1,t:"Revisión protésica en un tiempo."},
  {c:"PC.09.02",r:"PC",x:9,o:2,t:"Fractura periprotésica con revisión de la prótesis."},
  {c:"PC.09.03",r:"PC",x:9,o:3,t:"Primer tiempo de reconversión protésica infectada más espaciador."},
  {c:"PC.09.04",r:"PC",x:9,o:4,t:"Segundo tiempo de reconversión protésica infectada, colocación con reconstrucción con injerto de Banco de Tejidos."},
  {c:"PC.09.05",r:"PC",x:9,o:5,t:"Reemplazo total de cadera primario en displasias de cadera con plásticas de cotilo con injerto óseo o acortamiento femoral."},
  {c:"PC.09.06",r:"PC",x:9,o:6,t:"Segundo tiempo de reconversión protésica infectada sin reconstrucción ósea."},
  {c:"PC.09.07",r:"PC",x:9,o:7,t:"Reemplazo total de cadera no convencional, por secuela de fractura de acetábulo, osteosíntesis fallida de fémur proximal, secuela de artritis séptica, conversión de artrodesis."},
  {c:"PC.09.08",r:"PC",x:9,o:8,t:"Artroplastia de cadera con megaprótesis, por fractura periprotésica, o fractura grave de fémur."},
  {c:"PC.09.09",r:"PC",x:9,o:9,t:"Seudoartrosis de pelvis."},
  {c:"PC.09.10",r:"PC",x:9,o:10,t:"Injerto intercalar de metal 3D en fémur."},
  {c:"PC.09.11",r:"PC",x:9,o:11,t:"Reducción abierta de la luxación congénita de cadera combinada con osteotomía pélvica y femoral proximal combinada."},
  {c:"PC.09.12",r:"PC",x:9,o:12,t:"Tratamiento quirúrgico de una discrepancia de longitud mediante alargamiento óseo gradual (osteogenesis en distracción con tutor externo) o de un defecto óseo mediante transporte óseo, más de 5 centímetros."},
  {c:"PC.09.13",r:"PC",x:9,o:13,t:"Colgajos libres vascularizados (con neurorrafia o sin ella)."},
  {c:"PC.09.14",r:"PC",x:9,o:14,t:"Resecciones intralesionales (curetaje) de tumores benignos localmente agresivos o recidivantes (tumor de células gigantes, quiste óseo aneurismático, fibroma condromixoide, etc.), con adyuvancia local o sin ella, y con reconstrucción de cualquier tipo (endoprótesis, prótesis de revisión, cemento, injerto autólogo, etc.)"},
  {c:"PC.09.15",r:"PC",x:9,o:15,t:"Ampliaciones de márgenes realizadas en tumores de alto grado en pelvis."},
  {c:"PC.09.16",r:"PC",x:9,o:16,t:"Procedimientos óseos multinivel en neuroortopedia: tres niveles distribuidos en uno o ambos miembros; incluye todos los procedimientos tendinosos necesarios en cualquier nivel (niveles MI: 1-pelvis, 2-cadera/fémur proximal, 3-rodilla/fémur distal, 4-pierna distal/tobillo y 5-pie; MS: región equivalente de MI)."},
  {c:"PC.10.01",r:"PC",x:10,o:1,t:"Revisión de reemplazo total de cadera más plástica con injerto de Banco de Tejidos."},
  {c:"PC.10.02",r:"PC",x:10,o:2,t:"Reimplante de un miembro."},
  {c:"PC.10.03",r:"PC",x:10,o:3,t:"Amputación interilioabdominal/Hemipelvectomía interna y externa."},
  {c:"PC.10.04",r:"PC",x:10,o:4,t:"Reemplazo de fémur total."},
  {c:"PC.10.05",r:"PC",x:10,o:5,t:"Revisión de cadera con anillos o suplementos metálicos."},
  {c:"PC.10.06",r:"PC",x:10,o:6,t:"Resección ósea tumoral segmentaria. Tratamiento de tumores malignos (primarios o secundarios) o benignos agresivos (en bloque) más reconstrucción de cualquier tipo (endoprótesis, aloprótesis, injerto óseo masivo, espaciador de cemento, peroné vascularizado, etc.)"},
  {c:"PC.10.07",r:"PC",x:10,o:7,t:"Procedimientos óseos multinivel en neuroortopedia: cuatro niveles distribuidos en uno o ambos miembros; incluye todos los procedimientos tendinosos necesarios en cualquier nivel (niveles MI: 1-pelvis, 2-cadera/fémur proximal, 3-rodilla/fémur distal, 4-pierna distal/tobillo y 5-pie; MS: región equivalente de MI)."},
  {c:"PP.01.01",r:"PP",x:1,o:1,t:"Infiltraciones. Artrocentesis evacuadora."},
  {c:"PP.01.02",r:"PP",x:1,o:2,t:"Inmovilizaciones enyesadas."},
  {c:"PP.01.03",r:"PP",x:1,o:3,t:"Sutura de herida simple, no quirúrgica."},
  {c:"PP.01.04",r:"PP",x:1,o:4,t:"Extracción de osteodesis percutáneas, en consultorio."},
  {c:"PP.01.05",r:"PP",x:1,o:5,t:"Drenaje de un hematoma subungueal, por medio de la perforación única o múltiple de la uña."},
  {c:"PP.01.06",r:"PP",x:1,o:6,t:"Cura oclusiva en pie neuropático."},
  {c:"PP.01.07",r:"PP",x:1,o:7,t:"Tracciones cutáneas."},
  {c:"PP.01.08",r:"PP",x:1,o:8,t:"Movilización bajo anestesia."},
  {c:"PP.01.09",r:"PP",x:1,o:9,t:"Evaluación bajo radioscopia en quirófano."},
  {c:"PP.01.10",r:"PP",x:1,o:10,t:"Artrografía o artroneumografía por punción, en medio quirúrgico y con intensificador de imágenes."},
  {c:"PP.02.01",r:"PP",x:2,o:1,t:"Reducciones incruentas o manipulaciones en fracturas o luxaciones, con anestesia local, plexual o general. Incluye yeso."},
  {c:"PP.02.02",r:"PP",x:2,o:2,t:"Extracciones de tutores externos como único procedimiento."},
  {c:"PP.02.03",r:"PP",x:2,o:3,t:"Tratamiento quirúrgico de uña encarnada. Onicectomía parcial o total. Matricectomía parcial o total (con cruentado óseo o sin él)"},
  {c:"PP.02.04",r:"PP",x:2,o:4,t:"Evacuación quirúrgica de hematomas y abscesos superficiales."},
  {c:"PP.02.05",r:"PP",x:2,o:5,t:"Toilette quirúrgica superficial (supraaponeurótica)"},
  {c:"PP.02.06",r:"PP",x:2,o:6,t:"Curación y/o cruentado de úlceras crónicas (incluye resección de hiperqueratosis y toma de muestras)"},
  {c:"PP.02.07",r:"PP",x:2,o:7,t:"Tracciones esqueléticas y revisión parcial (cuadro de Shanz o barra) de tutor externo."},
  {c:"PP.02.08",r:"PP",x:2,o:8,t:"Tracciones esqueléticas."},
  {c:"PP.02.09",r:"PP",x:2,o:9,t:"Extracción de osteodesis percutáneas en quirófano."},
  {c:"PP.02.10",r:"PP",x:2,o:10,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, hasta 2 grupos musculares, unilateral o bilateral."},
  {c:"PP.03.01",r:"PP",x:3,o:1,t:"Fracturas o luxaciones inestables. Osteodesis percutáneas."},
  {c:"PP.03.02",r:"PP",x:3,o:2,t:"Seudoexostosis de Haglund."},
  {c:"PP.03.03",r:"PP",x:3,o:3,t:"Tratamiento de dedos en garra, dedos en martillo, en mazo o dedo supraducto. (Más de 2, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.03.04",r:"PP",x:3,o:4,t:"Amputación de dedos pequeños. (Más de 2, agregar un 30% al valor de dicha complejidad)"},
  {c:"PP.03.05",r:"PP",x:3,o:5,t:"Artrotomía de dedos o empeine para exploración o en artromielitis."},
  {c:"PP.03.06",r:"PP",x:3,o:6,t:"Capsulorrafia, miorrafia."},
  {c:"PP.03.07",r:"PP",x:3,o:7,t:"Tenosinovectomías, en general a cielo abierto (excepto del Tendón de Aquiles)."},
  {c:"PP.03.08",r:"PP",x:3,o:8,t:"Tenotomía percutánea del tendón de Aquiles."},
  {c:"PP.03.09",r:"PP",x:3,o:9,t:"Tenotomías percutáneas en pie."},
  {c:"PP.03.10",r:"PP",x:3,o:10,t:"Extracción de ganglión."},
  {c:"PP.03.11",r:"PP",x:3,o:11,t:"Fasciotomía a cielo abierto."},
  {c:"PP.03.12",r:"PP",x:3,o:12,t:"Sinovectomía de pequeñas articulaciones."},
  {c:"PP.03.13",r:"PP",x:3,o:13,t:"Fibromatosis plantar, nódulo único."},
  {c:"PP.03.14",r:"PP",x:3,o:14,t:"Injerto libre de piel como único tratamiento."},
  {c:"PP.03.15",r:"PP",x:3,o:15,t:"Toilette quirúrgica profunda (incluye pie diabético) con colocación de sistema de aspiración continua o sin ella en pacientes sin osteosíntesis. Recambio de sistema VAC."},
  {c:"PP.03.16",r:"PP",x:3,o:16,t:"Incisión y drenaje de absceso profundo."},
  {c:"PP.03.17",r:"PP",x:3,o:17,t:"Biopsia por punción."},
  {c:"PP.03.18",r:"PP",x:3,o:18,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, 3 o 4 grupos musculares, unilateral o bilateral."},
  {c:"PP.04.01",r:"PP",x:4,o:1,t:"Fractura de falanges y metatarsianos., hasta dos. Reducción y osteosíntesis. (Más de dos, agregar un 30% al valor de dicha complejidad por cada hueso comprometido)"},
  {c:"PP.04.02",r:"PP",x:4,o:2,t:"Fractura expuesta, tratamiento sin osteosíntesis. Incluye VAC."},
  {c:"PP.04.03",r:"PP",x:4,o:3,t:"Extracción de material de osteosíntesis."},
  {c:"PP.04.04",r:"PP",x:4,o:4,t:"Espolón calcáneo. Fascitis plantar crónica proximal con exéresis del espolón o sin ella."},
  {c:"PP.04.05",r:"PP",x:4,o:5,t:"Secuestrectomía o extracción de cuerpo extraño en pie, tobillo o peroné."},
  {c:"PP.04.06",r:"PP",x:4,o:6,t:"Sutura en agudo de ligamentos del tobillo."},
  {c:"PP.04.07",r:"PP",x:4,o:7,t:"Tenosinovectomía a cielo abierto del Tendón de Aquiles."},
  {c:"PP.04.08",r:"PP",x:4,o:8,t:"Artroplastia por resección o artrodesis interfalángica de dedos. (Más de 2 dedos, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.04.09",r:"PP",x:4,o:9,t:"Denervaciones articulares."},
  {c:"PP.04.10",r:"PP",x:4,o:10,t:"Epifisiodesis."},
  {c:"PP.04.11",r:"PP",x:4,o:11,t:"Colgajos locales (por avance, rotatorios o zetaplastias)."},
  {c:"PP.04.12",r:"PP",x:4,o:12,t:"Enfermedad de Ledderhose. Fibromatosis plantar compleja."},
  {c:"PP.04.13",r:"PP",x:4,o:13,t:"Sindactilias simples. (Dos o más espacios, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.04.14",r:"PP",x:4,o:14,t:"Polidactilia simple. (Más de 2 dedos, agregar un 30% al valor de dicha complejidad)"},
  {c:"PP.04.15",r:"PP",x:4,o:15,t:"Exostectomía de mediopie."},
  {c:"PP.04.16",r:"PP",x:4,o:16,t:"Resección de huesos accesorios, o resección parcial de huesos del pie."},
  {c:"PP.04.17",r:"PP",x:4,o:17,t:"Resección de neuroma."},
  {c:"PP.04.18",r:"PP",x:4,o:18,t:"Tratamiento quirúrgico simple del neuroma de Morton."},
  {c:"PP.04.19",r:"PP",x:4,o:19,t:"Tumores benignos en partes blandas extra aponeuróticos o superficiales."},
  {c:"PP.04.20",r:"PP",x:4,o:20,t:"Tumores de partes blandas de menos de 3 cm."},
  {c:"PP.04.21",r:"PP",x:4,o:21,t:"Biopsia a cielo abierto. Biopsia guiada por imágenes por causa oncológica."},
  {c:"PP.04.22",r:"PP",x:4,o:22,t:"Toilette quirúrgica de osteosíntesis con conservación de implante y toma de biopsia."},
  {c:"PP.04.23",r:"PP",x:4,o:23,t:"Tratamiento de la espasticidad con infiltración con toxina botulínica, 5 o más grupos musculares, unilateral o bilateral"},
  {c:"PP.04.24",r:"PP",x:4,o:24,t:"Miofasciotomia multinivel 2 a 3 grupos musculares distribuidos en uno o ambos miembros inferiores (homologable a miembros superiores)"},
  {c:"PP.05.01",r:"PP",x:5,o:1,t:"Fracturas de más de 2 falanges o metatarsianos. Reducción y osteosíntesis."},
  {c:"PP.05.02",r:"PP",x:5,o:2,t:"Fracturas unimaleolares de tobillo. Reducción y osteosíntesis."},
  {c:"PP.05.03",r:"PP",x:5,o:3,t:"Tratamiento del hallux valgo simple (exostectomía y partes blandas)."},
  {c:"PP.05.04",r:"PP",x:5,o:4,t:"Tratamiento quirúrgico del hallux rigidus, varus o flexus."},
  {c:"PP.05.05",r:"PP",x:5,o:5,t:"Exostectomía percutánea del hallux valgo."},
  {c:"PP.05.06",r:"PP",x:5,o:6,t:"Amputación del hallux, uno o más rayos laterales o transmetatarsal."},
  {c:"PP.05.07",r:"PP",x:5,o:7,t:"Pie equino (alargamiento del tendón de Aquiles y fascia plantar)."},
  {c:"PP.05.08",r:"PP",x:5,o:8,t:"Antepie varo."},
  {c:"PP.05.09",r:"PP",x:5,o:9,t:"Artrodesis de pie (medio o retropié)."},
  {c:"PP.05.10",r:"PP",x:5,o:10,t:"Juanetillo de sastre abierto. Osteotomías correctivas de metatarsianos o falanges (más de dos, agregar 30%)."},
  {c:"PP.05.11",r:"PP",x:5,o:11,t:"Tenorrafia simple del tendón de Aquiles. Reparación de Aquiles por técnica mini invasiva."},
  {c:"PP.05.12",r:"PP",x:5,o:12,t:"Tenorrafia aguda del tibial anterior más inmovilización enyesada."},
  {c:"PP.05.13",r:"PP",x:5,o:13,t:"Reconstrucción de ligamentos de tobillo (inestabilidad crónica)."},
  {c:"PP.05.14",r:"PP",x:5,o:14,t:"Sindactilias compleja."},
  {c:"PP.05.15",r:"PP",x:5,o:15,t:"Pie plano adquirido del adulto (ruptura del tibial posterior). Reconstrucción sólo de partes blandas."},
  {c:"PP.05.16",r:"PP",x:5,o:16,t:"Tenólisis de tendones de pierna."},
  {c:"PP.05.17",r:"PP",x:5,o:17,t:"Bandas constrictivas congénitas en pierna (macrodactilia y pie hendido). Tratamiento quirúrgico del pie cavo mediante procedimientos de partes blandas."},
  {c:"PP.05.18",r:"PP",x:5,o:18,t:"Exostectomía del mediopie (en pacientes diabéticos), percutánea."},
  {c:"PP.05.19",r:"PP",x:5,o:19,t:"Seudoartrosis de metatarsianos centrales y quinto metatarsiano."},
  {c:"PP.05.20",r:"PP",x:5,o:20,t:"Prácticas endoscópicas simples: tenoscopias, fasciotomías, tenosinovectomías (excepto del tendón de Aquiles)."},
  {c:"PP.05.21",r:"PP",x:5,o:21,t:"Reparación o sutura de tendón flexor de la pierna. (Más de 2, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.05.22",r:"PP",x:5,o:22,t:"Reparación o sutura de tendón extensor de la pierna. (Más de 2, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.05.23",r:"PP",x:5,o:23,t:"Neurólisis de nervios periféricos: ciático poplíteo externo, musculocutáneo, tibial anterior, tibial posterior (túnel tarsiano) y safeno interno (cada uno por separado)"},
  {c:"PP.05.24",r:"PP",x:5,o:24,t:"Sección o tenoplastia del gastrocnemios (proximal y media pierna)"},
  {c:"PP.05.25",r:"PP",x:5,o:25,t:"Tratamiento abierto de la lesión tibioperónea superior o inferior (sindesmosis) en agudo."},
  {c:"PP.05.26",r:"PP",x:5,o:26,t:"Neuroma de Morton mediante neurólisis microquirúrgica con magnificación. Incluye cirugía percutánea."},
  {c:"PP.05.27",r:"PP",x:5,o:27,t:"Resección/curetaje de un tumor óseo benigno, cavitario o pediculado, sin injerto óseo (osteocondroma, tumores benignos periósticos, lesiones quísticas)"},
  {c:"PP.05.28",r:"PP",x:5,o:28,t:"Curetaje y relleno con injerto óseo de una lesión cavitaria benigna en falanges, metatarsianos y segunda fila del tarso."},
  {c:"PP.05.29",r:"PP",x:5,o:29,t:"Tumor benigno de partes blandas subaponeurótico de más de 3 cm, no agresivo localmente."},
  {c:"PP.05.30",r:"PP",x:5,o:30,t:"Resecciones acrales (tobillo y pie,) de tumores malignos de bajo grado o de grado intermedio de agresividad, o tumores benignos agresivos (recidivantes) de cualquier localización (superficiales o profundos)."},
  {c:"PP.05.31",r:"PP",x:5,o:31,t:"Procedimientos terapéuticos percutáneos guiados por imágenes (Tratamiento del quiste óseo, simple, termo-ablación percutánea, crio-ablación percutánea, alcoholización)"},
  {c:"PP.05.32",r:"PP",x:5,o:32,t:"Miofasciotomia multinivel 4 o 5 grupos musculares distribuidos en uno o ambos miembros inferiores (homologable a miembros superiores)"},
  {c:"PP.06.01",r:"PP",x:6,o:1,t:"Fractura diafisaria de tibia. Reducción y osteosíntesis. (con fractura de peroné o sin ella). Fractura de tibia distal. Reducción y osteosíntesis. Fractura expuesta de pierna. Toilette + fijación externa con tutor."},
  {c:"PP.06.02",r:"PP",x:6,o:2,t:"Fractura bimaleolar o equivalente bimaleolar, tibia y peroné (tipo B y C de Weber)"},
  {c:"PP.06.03",r:"PP",x:6,o:3,t:"Fractura astrágalo, calcáneo, huesos del tarso Incluye utilización de injerto. Reducción y osteosíntesis."},
  {c:"PP.06.04",r:"PP",x:6,o:4,t:"Artroplastia protésica del hallux."},
  {c:"PP.06.05",r:"PP",x:6,o:5,t:"Tratamiento del hallux valgo complejo (partes blandas y osteotomía del 1er rayo)"},
  {c:"PP.06.06",r:"PP",x:6,o:6,t:"Tratamiento del hallux valgo completo, percutáneo."},
  {c:"PP.06.07",r:"PP",x:6,o:7,t:"Artroscopía simple de tobillo y pie. Sinovectomías, impingement sinovial u óseo anterior o posterior."},
  {c:"PP.06.08",r:"PP",x:6,o:8,t:"Osteotomía de huesos del pie, tibia o peroné."},
  {c:"PP.06.09",r:"PP",x:6,o:9,t:"Osteotomía percutánea de los metatarsianos centrales."},
  {c:"PP.06.10",r:"PP",x:6,o:10,t:"Osteotomía percutánea de quinto metatarsiano (Juanetillo)"},
  {c:"PP.06.11",r:"PP",x:6,o:11,t:"Artrodesis de tobillo a cielo abierto."},
  {c:"PP.06.12",r:"PP",x:6,o:12,t:"Artrodesis de pie de dos articulaciones (incluye tobillo)"},
  {c:"PP.06.13",r:"PP",x:6,o:13,t:"Tratamiento quirúrgico de la metatarsalgia central. Osteotomía múltiple de metatarsianos."},
  {c:"PP.06.14",r:"PP",x:6,o:14,t:"Pie plano complejo del adulto (tratamiento sobre partes blandas más osteotomías)"},
  {c:"PP.06.15",r:"PP",x:6,o:15,t:"Pie cavo del adulto (tratamiento sobre partes blandas más osteotomías)"},
  {c:"PP.06.16",r:"PP",x:6,o:16,t:"Resección ósea en pandiafisitis. Incluye colocación de cemento con antibiótico."},
  {c:"PP.06.17",r:"PP",x:6,o:17,t:"Amputación de rayo, pie, infrarrotuliana y suprarrotuliana por causa oncológica."},
  {c:"PP.06.18",r:"PP",x:6,o:18,t:"Pie bot simple (un solo gesto quirúrgico). Ponseti."},
  {c:"PP.06.19",r:"PP",x:6,o:19,t:"Pie plano, pie cavo del niño. Artrorrisis del tarso. Cirugías de partes blandas u osteotomías."},
  {c:"PP.06.20",r:"PP",x:6,o:20,t:"Pie plano, pie cavo complejo del niño. Coalisiones tarsales os tibialis, etc."},
  {c:"PP.06.21",r:"PP",x:6,o:21,t:"Resección de barra tarsal en el adulto."},
  {c:"PP.06.22",r:"PP",x:6,o:22,t:"Plástica del tendón de Aquiles (ruptura inveterada, plástica de aumentación)"},
  {c:"PP.06.23",r:"PP",x:6,o:23,t:"Amputación del retropié, tobillo o infrarrotuliana."},
  {c:"PP.06.24",r:"PP",x:6,o:24,t:"Ruptura inveterada del tibial anterior con transferencia de otro tendón del pie e injerto tendinoso de Banco de Tejidos."},
  {c:"PP.06.25",r:"PP",x:6,o:25,t:"Tenosinovectomía endoscópica del tendón de Aquiles (más denervación)"},
  {c:"PP.06.26",r:"PP",x:6,o:26,t:"Transferencia/s tendinosa/s en parálisis o secuela traumática."},
  {c:"PP.06.27",r:"PP",x:6,o:27,t:"Transferencias tendinosas o trasplantes, con obtención de injerto local."},
  {c:"PP.06.28",r:"PP",x:6,o:28,t:"Tendinopatía insercional del Tendón de Aquiles (con reinserción y exostosis de Haglund)."},
  {c:"PP.06.29",r:"PP",x:6,o:29,t:"Injerto de tendones flexores o extensores. (Más de 2, agregar un 30% al valor de dicha complejidad)."},
  {c:"PP.06.30",r:"PP",x:6,o:30,t:"Reparación de luxación de tendones peróneos."},
  {c:"PP.06.31",r:"PP",x:6,o:31,t:"Enclavado endomedular profiláctico en tibia."},
  {c:"PP.06.32",r:"PP",x:6,o:32,t:"Ampliaciones de márgenes en cirugía de tumores de bajo grado."},
  {c:"PP.06.33",r:"PP",x:6,o:33,t:"Curetaje y relleno con injerto óseo de una lesión cavitaria benigna en tibia, peroné, o huesos de la primera fila del tarso."},
  {c:"PP.06.34",r:"PP",x:6,o:34,t:"Curetaje y relleno con cemento (con o sin osteosíntesis) de una lesión metastásica en tibia."},
  {c:"PP.06.35",r:"PP",x:6,o:35,t:"Miofasciotomías multinivel 6 o más grupos musculares distribuidos en uno o ambos miembros inferiores (homologable a miembros superiores)"},
  {c:"PP.07.01",r:"PP",x:7,o:1,t:"Fractura expuesta de pierna. Toilette más osteosíntesis definitiva en un tiempo."},
  {c:"PP.07.02",r:"PP",x:7,o:2,t:"Fractura de pilón tibial intraarticular y peroné. Reducción y osteosíntesis. Incluye asistencia artroscópica. Fractura trimaleolar de tobillo (reducción y osteosíntesis de los tres maléolos)"},
  {c:"PP.07.03",r:"PP",x:7,o:3,t:"Osteosíntesis de calcáneo (con injerto o sin él) más artrodesis subastragalina (Dambleé)"},
  {c:"PP.07.04",r:"PP",x:7,o:4,t:"Resección total ósea como único tratamiento de tibia y peroné, astrágalo o calcáneo."},
  {c:"PP.07.05",r:"PP",x:7,o:5,t:"Alargamientos óseos. Acortamientos de miembro."},
  {c:"PP.07.06",r:"PP",x:7,o:6,t:"Osteotomías múltiples en tibia para corrección de defecto rotacional o angulares."},
  {c:"PP.07.07",r:"PP",x:7,o:7,t:"Antepié completo. Tratamiento del hallux valgo complejo (partes blandas y osteotomía del 1er rayo) más tratamiento de asociaciones (dedos menores) como dedo en garra, dedo en maso, etc."},
  {c:"PP.07.08",r:"PP",x:7,o:8,t:"Artroscopía compleja de tobillo: microfracturas, artrodesis, fasciotomías por síndrome compartimental, transplante osteocondral, reconstrucciones ligamentarias, etc."},
  {c:"PP.07.09",r:"PP",x:7,o:9,t:"Artroplastia articular de tobillo o pie con injerto osteocondral."},
  {c:"PP.07.10",r:"PP",x:7,o:10,t:"Artroplastia de tobillo no protésica (mosaicoplastia)."},
  {c:"PP.07.11",r:"PP",x:7,o:11,t:"Artroplastia protésica del hallux con osteotomías o artrodesis interfalángica y cuneometatarsiana."},
  {c:"PP.07.12",r:"PP",x:7,o:12,t:"Artroplastia protésica de dedos menores."},
  {c:"PP.07.13",r:"PP",x:7,o:13,t:"Artrodesis de tres articulaciones (triple artrodesis)"},
  {c:"PP.07.14",r:"PP",x:7,o:14,t:"Seudoartrosis de tibia. Seudoartrosis de mediopié y retropié."},
  {c:"PP.07.15",r:"PP",x:7,o:15,t:"Osteotomía de los 5 rayos del pié."},
  {c:"PP.07.16",r:"PP",x:7,o:16,t:"Pie plano complejo (tratamiento sobre partes blandas más osteotomía medializante de calcáneo más alargamiento de columna externa, eventual alargamiento del tendón de Aquiles)"},
  {c:"PP.07.17",r:"PP",x:7,o:17,t:"Neurorrafia de nervios periféricos de troncos terminales (plexo lumbosacro ciático, ciático poplíteo externo, ciático poplíteo interno, etc.)"},
  {c:"PP.07.18",r:"PP",x:7,o:18,t:"Injerto de colaterales nerviosos en pie. (Más de 2, agregar un 30% al valor de dicha complejidad)"},
  {c:"PP.07.19",r:"PP",x:7,o:19,t:"Cross leg. Incluye injerto."},
  {c:"PP.07.20",r:"PP",x:7,o:20,t:"Tratamiento quirúrgico de la osteomielitis crónica mediante saucerización."},
  {c:"PP.07.21",r:"PP",x:7,o:21,t:"Resección oncológica que comprometa un compartimiento de pierna o pie."},
  {c:"PP.08.01",r:"PP",x:8,o:1,t:"Artroplastia protésica de tobillo."},
  {c:"PP.08.02",r:"PP",x:8,o:2,t:"Artrodesis panastragalina con osteosíntesis (cuatro articulaciones)"},
  {c:"PP.08.03",r:"PP",x:8,o:3,t:"Pie bot (equino varo supinado-convexo congénito-astrágalo vertical) y pie bot secuelar"},
  {c:"PP.08.04",r:"PP",x:8,o:4,t:"Pie plano complejo (tratamiento sobre partes blandas más osteotomía medializante de calcáneo más alargamiento de columna externa más osteotomía del 1er metatarsiano, eventual alargamiento del tendón de Aquiles)"},
  {c:"PP.08.05",r:"PP",x:8,o:5,t:"Colgajos pediculados en isla. Incluye injerto de piel en zona dadora."},
  {c:"PP.08.06",r:"PP",x:8,o:6,t:"Tumor benigno de partes blandas subaponeurótico., mayor de 3 cm, agresivo localmente (p. ej., fibromatosis agresiva)"},
  {c:"PP.08.07",r:"PP",x:8,o:7,t:"Ampliaciones de márgenes en cirugía de tumores de alto grado."},
  {c:"PP.08.08",r:"PP",x:8,o:8,t:"Tratamiento de tumores malignos o benignos agresivos con resecciones óseas tumorales segmentarias (en bloque) sin reconstrucción."},
  {c:"PP.08.09",r:"PP",x:8,o:9,t:"Pie de Charcot. Osteotomías + triple artrodesis de retropié o tobillo con osteosíntesis rígidas o fijadores externos."},
  {c:"PP.08.10",r:"PP",x:8,o:10,t:"Tratamiento quirúrgico de los defectos longitudinales y pseudartrosis congénita de la pierna."},
  {c:"PP.08.11",r:"PP",x:8,o:11,t:"Toma y aplicación de un colgajo, en isla con pedículo o neurovascular (island-flap). Incluye el cierre del lecho dador con un injerto de piel."},
  {c:"PP.09.01",r:"PP",x:9,o:1,t:"Revisión de artroplastía protésica de tobillo."},
  {c:"PP.09.02",r:"PP",x:9,o:2,t:"Colgajos libres vascularizados (con neurorrafia o sin ella)."},
  {c:"PP.09.03",r:"PP",x:9,o:3,t:"Reimplante del hallux."},
  {c:"PP.09.04",r:"PP",x:9,o:4,t:"Artroplastia protésica de tobillo con osteotomías correctivas, alineación de pierna, retropié o mediopié, o plásticas ligamentarias por inestabilidad medial."},
  {c:"PP.09.05",r:"PP",x:9,o:5,t:"Resecciones intralesionales (curetaje) de tumores benignos localmente agresivos o recidivantes (tumor de células gigantes, quiste óseo aneurismático, fibroma condromixoide, etc.), con adyuvancia local o sin ella, y con reconstrucción de cualquier tipo (endoprótesis, prótesis de revisión, cemento, injerto autólogo, etc.)."},
  {c:"PP.10.01",r:"PP",x:10,o:1,t:"Reimplante de pie o pierna."},
  {c:"PP.10.02",r:"PP",x:10,o:2,t:"Resección ósea tumoral segmentaria. Tratamiento de tumores malignos (primarios o secundarios) o benignos agresivos (en bloque) más reconstrucción de cualquier tipo (endoprótesis, aloprótesis, injerto óseo masivo, espaciador de cemento, peroné vascularizado, etc.)"},
  {c:"RO.01.01",r:"RO",x:1,o:1,t:"Infiltración. Artrocentesis."},
  {c:"RO.01.02",r:"RO",x:1,o:2,t:"Calza de yeso, férula posterior."},
  {c:"RO.01.03",r:"RO",x:1,o:3,t:"Sutura de herida simple, no quirúrgica."},
  {c:"RO.01.04",r:"RO",x:1,o:4,t:"Extracción de osteodesis percutánea en consultorio."},
  {c:"RO.01.05",r:"RO",x:1,o:5,t:"Tracción partes blandas alrededor de la rodilla."},
  {c:"RO.01.06",r:"RO",x:1,o:6,t:"Reducción incruenta de rodilla bloqueada por lesión meniscal, con o sin anestesia intraarticular."},
  {c:"RO.01.07",r:"RO",x:1,o:7,t:"Movilización bajo anestesia."},
  {c:"RO.01.08",r:"RO",x:1,o:8,t:"Artrografía o artroneumografía por punción, en medio quirúrgico y con intensificador de imágenes"},
  {c:"RO.02.01",r:"RO",x:2,o:1,t:"Reducción incruenta de fractura de rodilla, con anestesia local o general. Incluye inmovilización enyesada"},
  {c:"RO.02.02",r:"RO",x:2,o:2,t:"Reducción de luxación de rótula. Con yeso o sin él."},
  {c:"RO.02.03",r:"RO",x:2,o:3,t:"Tracciones esqueléticas"},
  {c:"RO.02.04",r:"RO",x:2,o:4,t:"Toilette quirúrgica superficial (supraaponeurótica)"},
  {c:"RO.02.05",r:"RO",x:2,o:5,t:"Extracción de osteodesis percutáneas, con anestesia en quirófano"},
  {c:"RO.03.01",r:"RO",x:3,o:1,t:"Capsulorrafia. Con yeso o sin él."},
  {c:"RO.03.02",r:"RO",x:3,o:2,t:"Miorrafias. Fasciotomías."},
  {c:"RO.03.03",r:"RO",x:3,o:3,t:"Biopsias por punción."},
  {c:"RO.04.01",r:"RO",x:4,o:1,t:"Toilette en fracturas expuestas, sin tratamiento óseo definitivo."},
  {c:"RO.04.02",r:"RO",x:4,o:2,t:"Tratamiento de la osteocondritis rotuliana o femoral. Ratas intraarticulares. Tratamiento quirúrgico de las osteocondritis de la TAT secuelar."},
  {c:"RO.04.03",r:"RO",x:4,o:3,t:"Sutura en agudo de ligamento lateral interno o externo. Incluye yeso."},
  {c:"RO.04.04",r:"RO",x:4,o:4,t:"Hemipatelectomía. Patelectomía. Incluye yeso."},
  {c:"RO.04.05",r:"RO",x:4,o:5,t:"Tenorrafias simples en rodilla (p. ej., tendón cuadricipital, tendón rotuliano, etc.). Incluye yeso."},
  {c:"RO.04.06",r:"RO",x:4,o:6,t:"Extracción de material de osteosíntesis. Extracción de cuerpo extraño profundo."},
  {c:"RO.04.07",r:"RO",x:4,o:7,t:"Epifisiodesis."},
  {c:"RO.04.08",r:"RO",x:4,o:8,t:"Biopsia a cielo abierto. Biopsia guiada por imágenes por causa oncológica."},
  {c:"RO.04.09",r:"RO",x:4,o:9,t:"Tumores de partes blandas, subaponeuróticos, de menos de 3 cm."},
  {c:"RO.05.01",r:"RO",x:5,o:1,t:"Fractura de rótula. Reducción y osteosíntesis. Incluye yeso."},
  {c:"RO.05.02",r:"RO",x:5,o:2,t:"Resección del quiste de Baker."},
  {c:"RO.05.03",r:"RO",x:5,o:3,t:"Sutura de ligamentos laterales más menisectomía."},
  {c:"RO.05.04",r:"RO",x:5,o:4,t:"Sutura de ligamentos laterales más sutura de cruzados."},
  {c:"RO.05.05",r:"RO",x:5,o:5,t:"Plásticas ligamentarias extraarticulares."},
  {c:"RO.05.06",r:"RO",x:5,o:6,t:"Menisectomía simple a cielo abierto."},
  {c:"RO.05.07",r:"RO",x:5,o:7,t:"Sinovectomía a cielo abierto. Liberación capsular posterior de rodilla."},
  {c:"RO.05.08",r:"RO",x:5,o:8,t:"Tratamiento de la artritis séptica. Artrotomía. Curetaje en la osteomielitis de rodilla."},
  {c:"RO.05.09",r:"RO",x:5,o:9,t:"Resección de un tumor óseo benigno, sin reconstrucción (osteocondroma, tumores benignos periósticos, lesiones quísticas)."},
  {c:"RO.05.10",r:"RO",x:5,o:10,t:"Tumores de partes blandas, subaponeuróticos, de más de 3 cm."},
  {c:"RO.05.11",r:"RO",x:5,o:11,t:"Procedimientos terapéuticos percutáneos guiados por imágenes (Tratamiento del quiste óseo, simple, termo-ablación percutánea, crio-ablación percutánea, alcoholización)"},
  {c:"RO.06.01",r:"RO",x:6,o:1,t:"Fractura de un platillo tibial. Fractura con compromiso intraarticular o hundimiento. Reducción y osteosíntesis. Incluye injerto óseo."},
  {c:"RO.06.02",r:"RO",x:6,o:2,t:"Fractura de un cóndilo femoral. Reducción y Osteosintesis. Facturas expuestas alrededor de la rodilla, toilette mas colocación de tutor externo."},
  {c:"RO.06.03",r:"RO",x:6,o:3,t:"Artroscopía simple: lavado, toilette, menisectomía, realineación patelofemoral, plicas, sinovectomía, extracción de cuerpo libre."},
  {c:"RO.06.04",r:"RO",x:6,o:4,t:"Reosteosíntesis de rótula. Seudoartrosis de rótula (incluye extracción de material)"},
  {c:"RO.06.05",r:"RO",x:6,o:5,t:"Reconstrucción de ligamentos cruzados a cielo abierto."},
  {c:"RO.06.06",r:"RO",x:6,o:6,t:"Amputación infrarrotuliana o suprarrotuliana."},
  {c:"RO.06.07",r:"RO",x:6,o:7,t:"Tenotomías múltiples deflexoras de rodilla con capsulotomía o sin ella. (Bilateral, agregar un 30% al valor de dicha complejidad)."},
  {c:"RO.06.08",r:"RO",x:6,o:8,t:"Tratamiento quirúrgico de la luxación congénita de la rodilla."},
  {c:"RO.06.09",r:"RO",x:6,o:9,t:"Tratamiento quirúrgico de una discrepancia de longitud mediante técnica de epifisiodesis. Tratamiento quirúrgico de una deformidad angular mediante técnica de hemiepifisiodesis en un solo nivel (modulación fisaria)"},
  {c:"RO.06.10",r:"RO",x:6,o:10,t:"Ampliaciones de márgenes en cirugía de tumores de bajo grado."},
  {c:"RO.07.01",r:"RO",x:7,o:1,t:"Fractura de un platillo tibial. Fractura con compromiso intraarticular o hundimiento. Reducción y osteosíntesis. Incluye injerto óseo con control y asistencia artroscópica."},
  {c:"RO.07.02",r:"RO",x:7,o:2,t:"Fractura de fémur distal extrarticular o articular simple. Reducción y Osteosíntesis."},
  {c:"RO.07.03",r:"RO",x:7,o:3,t:"Artroscopía compleja de rodilla (LCA, LCP, transporte osteocondral, cultivo condrocitos, sutura meniscal)"},
  {c:"RO.07.04",r:"RO",x:7,o:4,t:"Tratamiento de la luxación recidivante de rótula en el niño o en el adulto. Reconstrucción del ligamento medial (LPFM). Transposición de la Tuberosidad anterior de la tibia (TAT). Incluye asistencia artroscópica."},
  {c:"RO.07.05",r:"RO",x:7,o:5,t:"Osteotomía valguizante de tibia. (Incluye asistencia artroscópica). Osteotomía deflexora. Osteotomía varizante femoral."},
  {c:"RO.07.06",r:"RO",x:7,o:6,t:"Artrodesis de rodilla simple."},
  {c:"RO.07.07",r:"RO",x:7,o:7,t:"Artroplastia de superficie (una sola superficie)"},
  {c:"RO.08.01",r:"RO",x:8,o:1,t:"Fractura de ambos platillos tibiales. Reducción y osteosíntesis por doble abordaje, fracturas con compromiso intraarticular o hundimiento. Incluye injerto óseo. Incluye asistencia artroscópica."},
  {c:"RO.08.02",r:"RO",x:8,o:2,t:"Fractura de fémur distal, intraarticular compleja, con artrotomía y reducción abierta."},
  {c:"RO.08.04",r:"RO",x:8,o:4,t:"Revisión artroscópica del LCA o del LCP. Incluye utilización de injertos."},
  {c:"RO.08.05",r:"RO",x:8,o:5,t:"Reconstrucción de LCA o LCP más plásticas en ligamentos laterales. Incluye el uso de injertos."},
  {c:"RO.08.06",r:"RO",x:8,o:6,t:"Tratamiento quirúrgico de la luxación grave de la rodilla. Lesión de Harry Platt (lesión de ligamentos laterales, cruzados y menisco)."},
  {c:"RO.08.07",r:"RO",x:8,o:7,t:"Fractura periprotésica de rodilla, sin revisión protésica."},
  {c:"RO.08.08",r:"RO",x:8,o:8,t:"Reconstrucción del aparato extensor, en reemplazo total de rodilla sin aloinjerto."},
  {c:"RO.08.09",r:"RO",x:8,o:9,t:"Aloinjerto de aparato extensor, sin recambio protésico"},
  {c:"RO.08.10",r:"RO",x:8,o:10,t:"Osteotomía tibial con reconstrucción de ligamento cruzado anterior."},
  {c:"RO.08.11",r:"RO",x:8,o:11,t:"Doble osteotomía con correcciones de desejes por secuelas de fracturas alrededor de la rodilla"},
  {c:"RO.08.12",r:"RO",x:8,o:12,t:"Seudoartrosis de fémur distal o tibia proximal."},
  {c:"RO.08.13",r:"RO",x:8,o:13,t:"Luxación congénita de la rótula en el niño."},
  {c:"RO.08.14",r:"RO",x:8,o:14,t:"Ampliaciones de márgenes en cirugía de tumores de alto grado."},
  {c:"RO.08.15",r:"RO",x:8,o:15,t:"Resección o curetaje de lesión tumoral cavitaria con relleno óseo. (Excluye TCG)"},
  {c:"RO.09.01",r:"RO",x:9,o:1,t:"Revisión de reemplazo total de rodilla en un tiempo."},
  {c:"RO.09.02",r:"RO",x:9,o:2,t:"Primer tiempo de reconversión de reemplazo total de rodilla infectado o no, más espaciador."},
  {c:"RO.09.03",r:"RO",x:9,o:3,t:"Segundo tiempo de reimplante de reemplazo total de rodilla infectado, sin reconstrucción ósea."},
  {c:"RO.09.04",r:"RO",x:9,o:4,t:"Extracción de reemplazo total de rodilla infectado más artrodesis."},
  {c:"RO.09.05",r:"RO",x:9,o:5,t:"Fractura periprotésica de rodilla, con revisión protésica."},
  {c:"RO.09.06",r:"RO",x:9,o:6,t:"Reemplazo total de rodilla primario, en pacientes con deformidad extraarticular femoral o tibial, que implique osteotomías correctivas."},
  {c:"RO.09.07",r:"RO",x:9,o:7,t:"Reconstrucción artroscópica de LCA + LCP en un tiempo. Incluye la plástica de los ligamentos colaterales y de los injertos utilizados."},
  {c:"RO.09.08",r:"RO",x:9,o:8,t:"Resecciones intralesionales (curetaje) de tumores benignos localmente agresivos o recidivantes, (tumor de células gigantes, quiste óseo aneurismático, fibroma condromixoide, etc.), con adyuvancia local o sin ella, y con reconstrucción de cualquier tipo (endoprótesis, prótesis de revisión, cemento, injerto autólogo, etc.)"},
  {c:"RO.09.09",r:"RO",x:9,o:9,t:"Transplante meniscal como único procedimiento."},
  {c:"RO.10.01",r:"RO",x:10,o:1,t:"Revisión de un reemplazo total de rodilla, más reconstrucción con injerto óseo de Banco de Tejidos"},
  {c:"RO.10.02",r:"RO",x:10,o:2,t:"Segundo tiempo de reconversión de reemplazo total de rodilla, más reconstrucción ósea con injerto óseo de Banco de Tejidos"},
  {c:"RO.10.03",r:"RO",x:10,o:3,t:"Aloinjerto de aparato extensor, con recambio protésico"},
  {c:"RO.10.04",r:"RO",x:10,o:4,t:"Resección ósea tumoral segmentaria. Tratamiento de tumores malignos (primarios o secundarios) o benignos agresivos (en bloque) más reconstrucción de cualquier tipo (endoprótesis, aloprótesis, injerto óseo masivo, espaciador de cemento, peroné vascularizado, etc.)"},
  {c:"RO.10.05",r:"RO",x:10,o:5,t:"Prótesis de resección tumoral en rodilla, por revisión o fractura compleja"},
  {c:"RO.10.06",r:"RO",x:10,o:6,t:"Transplante meniscal asociado a otro procedimiento como osteotmia alrededor de la rodilla y /o reconstrucción del LCA"},
].map(function(e){ return { codigo:e.c, region:e.r, complejidad:e.x, orden:e.o, texto:e.t }; });

var NUN_INDEX = (function(){ var m={}; for (var i=0;i<NUN_CODIGOS.length;i++) m[NUN_CODIGOS[i].codigo]=NUN_CODIGOS[i]; return m; })();

// Normaliza 'ms 4 1', 'MS0401', 'ms.4.1' -> 'MS.04.01'. Devuelve null si no matchea.
function nunNormalizarCodigo(raw){
  if(!raw) return null;
  var s=String(raw).toUpperCase().replace(/\s+/g,'');
  var m=s.match(/^([A-Z]{2})[.\-]?(\d{1,2})[.\-]?(\d{1,2})$/);
  if(!m) return null;
  var reg=m[1];
  if(!NUN_REGIONES[reg]) return null;
  return reg+'.'+('0'+m[2]).slice(-2)+'.'+('0'+m[3]).slice(-2);
}

function nunBuscar(raw){
  var cod=nunNormalizarCodigo(raw);
  return cod ? (NUN_INDEX[cod]||null) : null;
}

// Describe un código para mostrar en la UI: 'MS.06.02 — C6 Miembro superior — Fracturas del radio distal…'
function nunDescribir(raw){
  var e=nunBuscar(raw);
  if(!e) return null;
  return e.codigo+' — C'+e.complejidad+' '+NUN_REGIONES[e.region]+' — '+e.texto;
}

if (typeof window !== 'undefined') { window.NUN_CODIGOS=NUN_CODIGOS; window.NUN_INDEX=NUN_INDEX; window.NUN_NORMAS=NUN_NORMAS; window.NUN_REGIONES=NUN_REGIONES; window.nunBuscar=nunBuscar; window.nunDescribir=nunDescribir; window.nunNormalizarCodigo=nunNormalizarCodigo; }
